### ISSUE TITLE
Keep getting error java.lang.StackOverflowError

### ISSUE THREAD

**Issue by IAY-DGTERA** [trinhanhngoc/pycharm-odoo#225]
Plugin Version 2022.7

PyCharm 2022.2.4 (Community Edition)
Build #PC-222.4459.20, built on November 17, 2022
Runtime version: 17.0.5+7-b469.71 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-132-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 1926M
Cores: 16
Registry:
    debugger.watches.in.variables=false

Non-Bundled Plugins:
    com.markskelton.one-dark-theme (5.7.1)
    XPathView (222.4459.16)
    GrepConsole (12.15.211.6693.1)
    net.seesharpsoft.intellij.plugins.csv (3.0.1-222)
    zielu.gittoolbox (212.10.1)
    mobi.hsz.idea.gitignore (4.4.2)
    dev.ngocta.pycharm-odoo (2022.7)
    DBN (3.3.2571.0)

Current Desktop: ubuntu:GNOME

java.lang.StackOverflowError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:564)
	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:591)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:672)
	at com.intellij.concurrency.JobLauncherImpl.processQueue(JobLauncherImpl.java:357)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.processInOrder(InspectionRunner.java:293)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.visitElements(InspectionRunner.java:268)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$inspect$5(InspectionRunner.java:130)
	at com.intellij.codeInspection.InspectionEngine.withSession(InspectionEngine.java:226)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.inspect(InspectionRunner.java:109)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:131)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:97)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:215)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:184)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.StackOverflowError
	at com.intellij.psi.impl.source.PsiFileImpl.isValid(PsiFileImpl.java:135)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:637)
	at com.jetbrains.python.psi.resolve.PythonPathCache.get(PythonPathCache.java:50)
	at com.jetbrains.python.psi.resolve.PyResolveImportUtil.resolveQualifiedName(PyResolveImportUtil.kt:68)
	at com.jetbrains.python.pyi.PyiUtil.getOriginalFile(PyiUtil.java:181)
	at com.jetbrains.python.pyi.PyiUtil.getOriginalElement(PyiUtil.java:72)
	at dev.ngocta.pycharm.odoo.python.fixes.PyStubModuleMembersProvider.resolveMember(PyStubModuleMembersProvider.java:38)
	at com.jetbrains.python.psi.types.PyModuleType.resolveByMembersProviders(PyModuleType.java:265)
	at com.jetbrains.python.psi.types.PyModuleType.resolveMemberInPackageOrModule(PyModuleType.java:110)
	at com.jetbrains.python.psi.types.PyModuleType.resolveMember(PyModuleType.java:73)
	at dev.ngocta.pycharm.odoo.python.fixes.PyStubModuleMembersProvider.resolveMember(PyStubModuleMembersProvider.java:41)
	at com.jetbrains.python.psi.types.PyModuleType.resolveByMembersProviders(PyModuleType.java:265)
	at com.jetbrains.python.psi.types.PyModuleType.resolveMemberInPackageOrModule(PyModuleType.java:110)
	at com.jetbrains.python.psi.types.PyModuleType.resolveMember(PyModuleType.java:73)
	at dev.ngocta.pycharm.odoo.python.fixes.PyStubModuleMembersProvider.resolveMember(PyStubModuleMembersProvider.java:41)
	at com.jetbrains.python.psi.types.PyModuleType.resolveByMembersProviders(PyModuleType.java:265)
	at com.jetbrains.python.psi.types.PyModuleType.resolveMemberInPackageOrModule(PyModuleType.java:110)
	at com.jetbrains.python.psi.types.PyModuleType.resolveMember(PyModuleType.java:73)
	at dev.ngocta.pycharm.odoo.python.fixes.PyStubModuleMembersProvider.resolveMember(PyStubModuleMembersProvider.java:41)
	at com.jetbrains.python.psi.types.PyModuleType.resolveByMembersProviders(PyModuleType.java:265)
	at com.jetbrains.python.psi.types.PyModuleType.resolveMemberInPackageOrModule(PyModuleType.java:110)
	at com.jetbrains.python.psi.types.PyModuleType.resolveMember(PyModuleType.java:73)
	at dev.ngocta.pycharm.odoo.python.fixes.PyStubModuleMembersProvider.resolveMember(PyStubModuleMembersProvider.java:41)
	at com.jetbrains.python.psi.types.PyModuleType.resolveByMembersProviders(PyModuleType.java:265)
	at com.jetbrains.python.psi.types.PyModuleType.resolveMemberInPackageOrModule(PyModuleType.java:110)
	at com.jetbrains.python.psi.types.PyModuleType.resolveMember(PyModuleType.java:73)
	at dev.ngocta.pycharm.odoo.python.fixes.PyStubModuleMembersProvider.resolveMember(PyStubModuleMembersProvider.java:41)
	at com.jetbrains.python.psi.types.PyModuleType.resolveByMembersProviders(PyModuleType.java:265)
	at com.jetbrains.python.psi.types.PyModuleType.resolveMemberInPackageOrModule(PyModuleType.java:110)
	at com.jetbrains.python.psi.types.PyModuleType.resolveMember(PyModuleType.java:73)
	at dev.ngocta.pycharm.odoo.python.fixes.PyStubModuleMembersProvider.resolveMember(PyStubModuleMembersProvider.java:41)
	at com.jetbrains.python.psi.types.PyModuleType.resolveByMembersProviders(PyModuleType.java:265)
	at com.jetbrains.python.psi.types.PyModuleType.resolveMemberInPackageOrModule(PyModuleType.java:110)
	at com.jetbrains.python.psi.types.PyModuleType.resolveMember(PyModuleType.java:73)
	at dev.ngocta.pycharm.odoo.python.fixes.PyStubModuleMembersProvider.resolveMember(PyStubModuleMembersProvider.java:41)
	at com.jetbrains.python.psi.types.PyModuleType.resolveByMembersProviders(PyModuleType.java:265)
	at com.jetbrains.python.psi.types.PyModuleType.resolveMemberInPackageOrModule(PyModuleType.java:110)
	at com.jetbrains.python.psi.types.PyModuleType.resolveMember(PyModuleType.java:73)
	at dev.ngocta.pycharm.odoo.python.fixes.PyStubModuleMembersProvider.resolveMember(PyStubModuleMembersProvider.java:41)
	at com.jetbrains.python.psi.types.PyModuleType.resolveByMembersProviders(PyModuleType.java:265)
	at com.jetbrains.python.psi.types.PyModuleType.resolveMemberInPackageOrModule(PyModuleType.java:110)
	at com.jetbrains.python.psi.types.PyModuleType.resolveMember(PyModuleType.java:73)
	at dev.ngocta.pycharm.odoo.python.fixes.PyStubModuleMembersProvider.resolveMember(PyStubModuleMembersProvider.java:41)
	at com.jetbrains.python.psi.types.PyModuleType.resolveByMembersProviders(PyModuleType.java:265)
	at com.jetbrains.python.psi.types.PyModuleType.resolveMemberInPackageOrModule(PyModuleType.java:110)
	at com.jetbrains.python.psi.types.PyModuleType.resolveMember(PyModuleType.java:73)

**Comment by trinhanhngoc** [comment]
Hi @IAY-DGTERA 

Can you reproduce this error, such as opening a specific file. If the file causing this error is in the Odoo source code, please share me the link to it in github.com/odoo/odoo. Thanks!

**Comment by IAY-DGTERA** [comment]
Yes it caused when opening a specific file but it is not part of odoo it is a python script file i wrote using odooly lib @trinhanhngoc

**Comment by trinhanhngoc** [comment]
@IAY-DGTERA If you don't mind, can you share the script content with me? It will help me a lot in reproducing this error on my machine and fixing it. Thanks!

**Comment by IAY-DGTERA** [comment]
Yes Of course
here is the [gist](https://gist.github.com/IAY-DGTERA/f2c792f306b22ed4e16007162e4540fc)
@trinhanhngoc

**Comment by trinhanhngoc** [comment]
Hi @IAY-DGTERA ,

Honestly, I could not reproduce this error with the sample code you provided =)). However, I have made improvements to avoid this error. Please update the Odoo plugin to the new version 2022.7.1 to see if it solves your problem. Thanks for reporting!
