### ISSUE TITLE
Exception in Odoo plugin when parsing SQL string in Python code

### ISSUE THREAD

**Issue by mege-odoo** [trinhanhngoc/pycharm-odoo#339]
PyCharm version: ~~2023.3.3~~ 2022.3.3
Odoo plugin version: 2023.3.4 or 2023.3.3

Steps to reproduce:
1. Create a new project using the system interpreter and with an automatically created default main.py welcome script
2. In main.py, add a string containing SQL, like `x = "SELECT * FROM test_table"`
3. The Odoo plugin generates a traceback. This doesn't appear to block anything, it just pops up every time when opening any project containing SQL strings.

![Screenshot from 2023-03-27 14-33-41](https://user-images.githubusercontent.com/117735233/227942898-5d983e8a-16e3-4ddb-91a1-5ae4ed59c76e.png)
![Screenshot from 2023-03-27 14-33-56](https://user-images.githubusercontent.com/117735233/227942927-7b6be165-436b-4b90-8d0e-cca1b87f1284.png)
![Screenshot from 2023-03-27 14-34-17](https://user-images.githubusercontent.com/117735233/227942941-17d18dae-96b5-45d3-b080-55c7386044b6.png)

Full traceback:

java.lang.Throwable: Unbalanced tree. Most probably caused by unbalanced markers. Try calling setDebugMode(true) against PsiBuilder passed to identify exact location of the problem
language: Language: GenericSQL, 
context: '<none>'
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.lang.impl.PsiBuilderImpl.reportUnbalancedMarkers(PsiBuilderImpl.java:1095)
	at com.intellij.lang.impl.PsiBuilderImpl.assertMarkersBalanced(PsiBuilderImpl.java:1087)
	at com.intellij.lang.impl.PsiBuilderImpl.prepareLightTree(PsiBuilderImpl.java:1056)
	at com.intellij.lang.impl.PsiBuilderImpl.buildTree(PsiBuilderImpl.java:904)
	at com.intellij.lang.impl.PsiBuilderImpl.getTreeBuilt(PsiBuilderImpl.java:899)
	at com.intellij.sql.dialects.base.SqlParser.parse(SqlParser.java:118)
	at com.intellij.sql.psi.stubs.SqlFileElementType.doParseContents(SqlFileElementType.java:84)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:53)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.lambda$ensureParsed$2(LazyParseableElement.java:185)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:481)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:184)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:236)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:25)
	at com.intellij.psi.impl.source.tree.injected.InjectionRegistrarImpl.keepTreeFromChameleoningBack(InjectionRegistrarImpl.java:410)
	at com.intellij.psi.impl.source.tree.injected.InjectionRegistrarImpl.parseFile(InjectionRegistrarImpl.java:689)
	at com.intellij.psi.impl.source.tree.injected.InjectionRegistrarImpl.createAndRegisterInjected(InjectionRegistrarImpl.java:258)
	at com.intellij.psi.impl.source.tree.injected.InjectionRegistrarImpl.doneInjecting(InjectionRegistrarImpl.java:223)
	at com.jetbrains.python.codeInsight.PyInjectionUtil.registerStringLiteralInjection(PyInjectionUtil.java:80)
	at com.jetbrains.python.codeInsight.PyInjectorBase.registerInjection(PyInjectorBase.java:50)
	at com.jetbrains.python.intelliLang.PyConfigurationInjector.getLanguagesToInject(PyConfigurationInjector.java:40)
	at dev.ngocta.pycharm.odoo.sql.OdooSqlLanguageInjector.getLanguagesToInject(OdooSqlLanguageInjector.java:75)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.processInPlaceInjectorsFor(InjectedLanguageManagerImpl.java:442)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtilBase.probeElementsUp(InjectedLanguageUtilBase.java:240)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtilBase.enumerate(InjectedLanguageUtilBase.java:170)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.enumerateEx(InjectedLanguageManagerImpl.java:326)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.lambda$getInjectedPsiFiles$3(InjectedGeneralHighlightingPass.java:176)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1111)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:83)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:173)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:83)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Comment by mege-odoo** [comment]
The project doesn't have a data source configured.

**Comment by trinhanhngoc** [comment]
Hi @mege-odoo , I have tried many times but cannot reproduce the exception with PyCharm 2022.3.3 and Odoo plugin 2023.3.4

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/11208291/228113844-ef36a21e-5429-450d-944d-24e4a70cee2b.png">

```
at com.jetbrains.python.intelliLang.PyConfigurationInjector.getLanguagesToInject(PyConfigurationInjector.java:40)
at dev.ngocta.pycharm.odoo.sql.OdooSqlLanguageInjector.getLanguagesToInject(OdooSqlLanguageInjector.java:75)
```

Also, looking at the stacktrace, it's more like an internal PyCharm issue than an Odoo plugin issue. Like in Odoo we call `super()` in the overriding method and the exception is raised in the overridden method.

**Comment by mege-odoo** [comment]
Hi @trinhanhngoc , thanks for having checked. I'll investigate a bit further and see if I can reproduce in a cleaner environment or without the Odoo plugin.

**Comment by mege-odoo** [comment]
I had a typo in the originally reported PyCharm version, it was 2022.3.3 instead of 2023.3.3. The issue no longer reproduces on version 2023.1 which released last week.
