### ISSUE TITLE
Cannot load class dev.ngocta.pycharm.odoo.OdooVersion

### ISSUE THREAD

**Issue by Jerther** [trinhanhngoc/pycharm-odoo#343]
Hi!!

PyCharm version: 2023.1 CE
Odoo plugin version: 2023.3.4.231

Love your plugin! Well worth the license fee!!

I started having this error after I updated PyCharm and the Odoo plugin. This happens when starting PyCharm, and every now and then when working. Not sure exactly what's causing this... The plugin seems to work mostly fine.

```
java.lang.BootstrapMethodError: com.intellij.diagnostic.PluginException: Cannot load class dev.ngocta.pycharm.odoo.OdooVersion (
  error: org/apache/maven/artifact/versioning/ComparableVersion,
  classLoader=PluginClassLoader(plugin=PluginDescriptor(name=Odoo, id=dev.ngocta.pycharm-odoo, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/PyCharmCE2023.1/Odoo, version=2023.3.4.231, package=null, isBundled=false), packagePrefix=null, instanceId=52, state=active)
)
	at dev.ngocta.pycharm.odoo.OdooUtils.getOdooVersion(OdooUtils.java:183)
	at dev.ngocta.pycharm.odoo.xml.OdooXmlUtils.getRootViewElementDescriptor(OdooXmlUtils.java:379)
	at dev.ngocta.pycharm.odoo.xml.OdooRngElementDescriptor.getElementDescriptor(OdooRngElementDescriptor.java:64)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.computeElementDescriptor(XmlTagDelegate.java:471)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate$1.compute(XmlTagDelegate.java:438)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:244)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:244)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:245)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:69)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.getDescriptor(XmlTagDelegate.java:434)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.getDescriptor(XmlTagImpl.java:120)
	at com.intellij.xml.XmlCustomTagHighlightingPass$doCollectInformation$1.visitXmlTag(XmlCustomTagHighlightingPass.kt:48)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.accept(XmlTagImpl.java:268)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:53)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:10)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:62)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:49)
	at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:62)
	at com.intellij.psi.XmlRecursiveElementWalkingVisitor.visitElement(XmlRecursiveElementWalkingVisitor.java:40)
	at com.intellij.psi.XmlElementVisitor.visitXmlElement(XmlElementVisitor.java:23)
	at com.intellij.psi.XmlElementVisitor.visitXmlDocument(XmlElementVisitor.java:43)
	at com.intellij.psi.impl.source.xml.XmlDocumentImpl.accept(XmlDocumentImpl.java:52)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:185)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:754)
	at com.intellij.xml.XmlCustomTagHighlightingPass.doCollectInformation(XmlCustomTagHighlightingPass.kt:45)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:382)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1102)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:374)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:373)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:349)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:229)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:187)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:347)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: com.intellij.diagnostic.PluginException: Cannot load class dev.ngocta.pycharm.odoo.OdooVersion (
  error: org/apache/maven/artifact/versioning/ComparableVersion,
  classLoader=PluginClassLoader(plugin=PluginDescriptor(name=Odoo, id=dev.ngocta.pycharm-odoo, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/PyCharmCE2023.1/Odoo, version=2023.3.4.231, package=null, isBundled=false), packagePrefix=null, instanceId=52, state=active)
)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.kt:325)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.kt:172)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 57 more
Caused by: java.lang.NoClassDefFoundError: org/apache/maven/artifact/versioning/ComparableVersion
	at java.base/java.lang.ClassLoader.defineClass2(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1103)
	at com.intellij.util.lang.UrlClassLoader.consumeClassData(UrlClassLoader.java:268)
	at com.intellij.util.lang.ZipResourceFile.findClass(ZipResourceFile.java:112)
	at com.intellij.util.lang.JarLoader.findClass(JarLoader.java:58)
	at com.intellij.util.lang.ClassPath.findClassInLoader(ClassPath.java:233)
	at com.intellij.util.lang.ClassPath.findClass(ClassPath.java:183)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.kt:320)
	... 60 more
Caused by: java.lang.ClassNotFoundException: org.apache.maven.artifact.versioning.ComparableVersion PluginClassLoader(plugin=PluginDescriptor(name=Odoo, id=dev.ngocta.pycharm-odoo, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/PyCharmCE2023.1/Odoo, version=2023.3.4.231, package=null, isBundled=false), packagePrefix=null, instanceId=52, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 68 more

```

I hope this is enough information.

**Comment by trinhanhngoc** [comment]
Hi @Jerther , today I will publish a new plugin version to address this issue.

**Comment by trinhanhngoc** [comment]
Hi @Jerther , the new version 2023.4.0 has been released with the fix for this issue. Thanks for the report.
