### ISSUE TITLE
PersistentEnumerator storage corrupted

### ISSUE THREAD

**Issue by sjpatel21** [trinhanhngoc/pycharm-odoo#396]
Stacktrace.txt

```
com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corrupted /home/osi/.cache/JetBrains/PyCharm2022.3/index/fileincludes/.perFileVersion/indexed_versions/indexed_versions
	at com.intellij.util.io.PersistentEnumeratorBase.catchCorruption(PersistentEnumeratorBase.java:628)
	at com.intellij.util.io.PersistentEnumeratorBase.doEnumerate(PersistentEnumeratorBase.java:272)
	at com.intellij.util.io.PersistentEnumeratorBase.tryEnumerate(PersistentEnumeratorBase.java:263)
	at com.intellij.util.io.PersistentMapImpl.doGet(PersistentMapImpl.java:587)
	at com.intellij.util.io.PersistentMapImpl.get(PersistentMapImpl.java:549)
	at com.intellij.util.io.PersistentHashMap.get(PersistentHashMap.java:169)
	at com.intellij.util.indexing.impl.perFileVersion.PersistentSubIndexerVersionEnumerator$MyEnumerator.enumerate(PersistentSubIndexerVersionEnumerator.java:22)
	at com.intellij.util.io.CachingEnumerator.enumerate(CachingEnumerator.java:75)
	at com.intellij.util.indexing.impl.perFileVersion.PersistentSubIndexerVersionEnumerator.enumerate(PersistentSubIndexerVersionEnumerator.java:60)
	at com.intellij.util.indexing.impl.perFileVersion.PersistentSubIndexerRetriever.getFileIndexerId(PersistentSubIndexerRetriever.java:103)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.lambda$getFileIndexMetaData$3(VfsAwareMapReduceIndex.java:205)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$4(CoreProgressManager.java:230)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:99)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:230)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.getFileIndexMetaData(VfsAwareMapReduceIndex.java:205)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.getFileIndexMetaData(VfsAwareMapReduceIndex.java:40)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.getFileIndexMetaData(CompositeInvertedIndexBase.java:170)
	at com.intellij.util.indexing.FileBasedIndexImpl.createSingleIndexValueApplier(FileBasedIndexImpl.java:1606)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$25(FileBasedIndexImpl.java:1473)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyWithProvidedValueIn(FileTypeManagerImpl.java:670)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1421)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1394)
	at com.intellij.util.indexing.FileBasedIndexImpl.processRefreshedFile(FileBasedIndexImpl.java:1342)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1743)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1740)
	at com.intellij.util.indexing.UpdateTask.process(UpdateTask.java:63)
	at com.intellij.util.indexing.UpdateTask.processAll(UpdateTask.java:32)
	at com.intellij.util.indexing.FileBasedIndexImpl.forceUpdate(FileBasedIndexImpl.java:1760)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:808)
	at com.intellij.util.indexing.FileBasedIndexEx.processExceptions(FileBasedIndexEx.java:322)
	at com.intellij.util.indexing.FileBasedIndexEx.getContainingFilesIterator(FileBasedIndexEx.java:269)
	at com.intellij.util.indexing.FileBasedIndexEx.getContainingFiles(FileBasedIndexEx.java:245)
	at com.intellij.util.indexing.FileBasedIndexImpl.getContainingFiles(FileBasedIndexImpl.java:1098)
	at dev.ngocta.pycharm.odoo.OdooEditorTabTitleProvider.getEditorTabTitle(OdooEditorTabTitleProvider.java:50)
	at com.intellij.openapi.fileEditor.impl.EditorTabPresentationUtil.getCustomEditorTabTitle(EditorTabPresentationUtil.java:34)
	at com.intellij.openapi.fileEditor.impl.EditorTabPresentationUtil.getEditorTabTitle(EditorTabPresentationUtil.java:19)
	at com.intellij.openapi.vfs.newvfs.VfsPresentationUtil.getPresentableNameForUI(VfsPresentationUtil.java:28)
	at com.intellij.ide.actions.SearchEverywherePsiRenderer.getElementText(SearchEverywherePsiRenderer.java:66)
	at com.intellij.ide.util.PsiElementListCellRenderer$1.getPresentableText(PsiElementListCellRenderer.java:416)
	at com.intellij.ide.util.PsiElementListCellRenderer.targetPresentation(PsiElementListCellRenderer.java:449)
	at com.intellij.ide.util.PsiElementListCellRenderer.computePresentation(PsiElementListCellRenderer.java:398)
	at com.intellij.ide.actions.searcheverywhere.PSIPresentationBgRendererWrapper.lambda$createCalculator$1(PSIPresentationBgRendererWrapper.java:75)
	at com.intellij.ide.actions.searcheverywhere.PSIPresentationBgRendererWrapper.element2presentation(PSIPresentationBgRendererWrapper.java:88)
	at com.intellij.ide.actions.searcheverywhere.PSIPresentationBgRendererWrapper.lambda$fetchWeightedElements$0(PSIPresentationBgRendererWrapper.java:68)
	at com.intellij.ide.actions.searcheverywhere.FileSearchEverywhereContributor.processElement(FileSearchEverywhereContributor.java:110)
	at com.intellij.ide.actions.searcheverywhere.AbstractGotoSEContributor.lambda$fetchWeightedElements$1(AbstractGotoSEContributor.java:245)
	at com.intellij.ide.actions.GotoFileItemProvider$SuffixMatches.lambda$processFiles$4(GotoFileItemProvider.java:423)
	at com.intellij.util.containers.ContainerUtil.process(ContainerUtil.java:702)
	at com.intellij.ide.actions.GotoFileItemProvider$SuffixMatches.processFiles(GotoFileItemProvider.java:425)
	at com.intellij.ide.actions.GotoFileItemProvider.processItemsForPattern(GotoFileItemProvider.java:109)
	at com.intellij.ide.actions.GotoFileItemProvider.doFilterElements(GotoFileItemProvider.java:81)
	at com.intellij.ide.actions.GotoFileItemProvider.lambda$filterElementsWithWeights$0(GotoFileItemProvider.java:62)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.actions.GotoFileItemProvider.filterElementsWithWeights(GotoFileItemProvider.java:62)
	at com.intellij.ide.actions.searcheverywhere.AbstractGotoSEContributor.lambda$fetchWeightedElements$4(AbstractGotoSEContributor.java:244)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1111)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:71)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:128)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:109)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:68)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:68)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:106)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:71)
	at com.intellij.ide.actions.searcheverywhere.AbstractGotoSEContributor.fetchWeightedElements(AbstractGotoSEContributor.java:270)
	at com.intellij.ide.actions.searcheverywhere.PSIPresentationBgRendererWrapper.fetchWeightedElements(PSIPresentationBgRendererWrapper.java:67)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ContributorSearchTask.run(MixedResultsSearcher.java:183)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:246)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

induced.txt

```
Following exceptions happened soon after this one, most probably they are induced.


2023-06-22T11:33:31.567
java.lang.Throwable: Assertion failed: getFileIndexMetaData() shouldn't have returned null.
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:254)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.setIndexedStateForFileOnFileIndexMetaData(VfsAwareMapReduceIndex.java:218)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.setIndexedStateForFileOnFileIndexMetaData(VfsAwareMapReduceIndex.java:40)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.setIndexedStateForFileOnFileIndexMetaData(CompositeInvertedIndexBase.java:188)
	at com.intellij.util.indexing.SingleIndexValueApplier.setIndexedState(SingleIndexValueApplier.java:90)
	at com.intellij.util.indexing.SingleIndexValueApplier.lambda$doApply$0(SingleIndexValueApplier.java:76)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:243)
	at com.intellij.util.indexing.SingleIndexValueApplier.doApply(SingleIndexValueApplier.java:72)
	at com.intellij.util.indexing.SingleIndexValueApplier.apply(SingleIndexValueApplier.java:55)
	at com.intellij.util.indexing.FileIndexesValuesApplier.apply(FileIndexesValuesApplier.java:113)
	at com.intellij.util.indexing.FileBasedIndexImpl.processRefreshedFile(FileBasedIndexImpl.java:1342)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1743)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1740)
	at com.intellij.util.indexing.UpdateTask.process(UpdateTask.java:63)
	at com.intellij.util.indexing.UpdateTask.processAll(UpdateTask.java:32)
	at com.intellij.util.indexing.FileBasedIndexImpl.forceUpdate(FileBasedIndexImpl.java:1760)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:808)
	at com.intellij.util.indexing.FileBasedIndexEx.processExceptions(FileBasedIndexEx.java:322)
	at com.intellij.util.indexing.FileBasedIndexEx.getContainingFilesIterator(FileBasedIndexEx.java:269)
	at com.intellij.util.indexing.FileBasedIndexEx.getContainingFiles(FileBasedIndexEx.java:245)
	at com.intellij.util.indexing.FileBasedIndexImpl.getContainingFiles(FileBasedIndexImpl.java:1098)
	at dev.ngocta.pycharm.odoo.OdooEditorTabTitleProvider.getEditorTabTitle(OdooEditorTabTitleProvider.java:50)
	at com.intellij.openapi.fileEditor.impl.EditorTabPresentationUtil.getCustomEditorTabTitle(EditorTabPresentationUtil.java:34)
	at com.intellij.openapi.fileEditor.impl.EditorTabPresentationUtil.getEditorTabTitle(EditorTabPresentationUtil.java:19)
	at com.intellij.openapi.vfs.newvfs.VfsPresentationUtil.getPresentableNameForUI(VfsPresentationUtil.java:28)
	at com.intellij.ide.actions.SearchEverywherePsiRenderer.getElementText(SearchEverywherePsiRenderer.java:66)
	at com.intellij.ide.util.PsiElementListCellRenderer$1.getPresentableText(PsiElementListCellRenderer.java:416)
	at com.intellij.ide.util.PsiElementListCellRenderer.targetPresentation(PsiElementListCellRenderer.java:449)
	at com.intellij.ide.util.PsiElementListCellRenderer.computePresentation(PsiElementListCellRenderer.java:398)
	at com.intellij.ide.actions.searcheverywhere.PSIPresentationBgRendererWrapper.lambda$createCalculator$1(PSIPresentationBgRendererWrapper.java:75)
	at com.intellij.ide.actions.searcheverywhere.PSIPresentationBgRendererWrapper.element2presentation(PSIPresentationBgRendererWrapper.java:88)
	at com.intellij.ide.actions.searcheverywhere.PSIPresentationBgRendererWrapper.lambda$fetchWeightedElements$0(PSIPresentationBgRendererWrapper.java:68)
	at com.intellij.ide.actions.searcheverywhere.FileSearchEverywhereContributor.processElement(FileSearchEverywhereContributor.java:110)
	at com.intellij.ide.actions.searcheverywhere.AbstractGotoSEContributor.lambda$fetchWeightedElements$1(AbstractGotoSEContributor.java:245)
	at com.intellij.ide.actions.GotoFileItemProvider$SuffixMatches.lambda$processFiles$4(GotoFileItemProvider.java:423)
	at com.intellij.util.containers.ContainerUtil.process(ContainerUtil.java:702)
	at com.intellij.ide.actions.GotoFileItemProvider$SuffixMatches.processFiles(GotoFileItemProvider.java:425)
	at com.intellij.ide.actions.GotoFileItemProvider.processItemsForPattern(GotoFileItemProvider.java:109)
	at com.intellij.ide.actions.GotoFileItemProvider.doFilterElements(GotoFileItemProvider.java:81)
	at com.intellij.ide.actions.GotoFileItemProvider.lambda$filterElementsWithWeights$0(GotoFileItemProvider.java:62)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.actions.GotoFileItemProvider.filterElementsWithWeights(GotoFileItemProvider.java:62)
	at com.intellij.ide.actions.searcheverywhere.AbstractGotoSEContributor.lambda$fetchWeightedElements$4(AbstractGotoSEContributor.java:244)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1111)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:71)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:128)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:109)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:68)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:68)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:106)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:71)
	at com.intellij.ide.actions.searcheverywhere.AbstractGotoSEContributor.fetchWeightedElements(AbstractGotoSEContributor.java:270)
	at com.intellij.ide.actions.searcheverywhere.PSIPresentationBgRendererWrapper.fetchWeightedElements(PSIPresentationBgRendererWrapper.java:67)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ContributorSearchTask.run(MixedResultsSearcher.java:183)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:246)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)



2023-06-22T11:33:31.570
java.lang.NullPointerException: Cannot read field "indexerId" because "fileData" is null
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.setIndexedStateForFileOnFileIndexMetaData(VfsAwareMapReduceIndex.java:220)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.setIndexedStateForFileOnFileIndexMetaData(VfsAwareMapReduceIndex.java:40)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.setIndexedStateForFileOnFileIndexMetaData(CompositeInvertedIndexBase.java:188)
	at com.intellij.util.indexing.SingleIndexValueApplier.setIndexedState(SingleIndexValueApplier.java:90)
	at com.intellij.util.indexing.SingleIndexValueApplier.lambda$doApply$0(SingleIndexValueApplier.java:76)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:243)
	at com.intellij.util.indexing.SingleIndexValueApplier.doApply(SingleIndexValueApplier.java:72)
	at com.intellij.util.indexing.SingleIndexValueApplier.apply(SingleIndexValueApplier.java:55)
	at com.intellij.util.indexing.FileIndexesValuesApplier.apply(FileIndexesValuesApplier.java:113)
	at com.intellij.util.indexing.FileBasedIndexImpl.processRefreshedFile(FileBasedIndexImpl.java:1342)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1743)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1740)
	at com.intellij.util.indexing.UpdateTask.process(UpdateTask.java:63)
	at com.intellij.util.indexing.UpdateTask.processAll(UpdateTask.java:32)
	at com.intellij.util.indexing.FileBasedIndexImpl.forceUpdate(FileBasedIndexImpl.java:1760)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:808)
	at com.intellij.util.indexing.FileBasedIndexEx.processExceptions(FileBasedIndexEx.java:322)
	at com.intellij.util.indexing.FileBasedIndexEx.getContainingFilesIterator(FileBasedIndexEx.java:269)
	at com.intellij.util.indexing.FileBasedIndexEx.getContainingFiles(FileBasedIndexEx.java:245)
	at com.intellij.util.indexing.FileBasedIndexImpl.getContainingFiles(FileBasedIndexImpl.java:1098)
	at dev.ngocta.pycharm.odoo.OdooEditorTabTitleProvider.getEditorTabTitle(OdooEditorTabTitleProvider.java:50)
	at com.intellij.openapi.fileEditor.impl.EditorTabPresentationUtil.getCustomEditorTabTitle(EditorTabPresentationUtil.java:34)
	at com.intellij.openapi.fileEditor.impl.EditorTabPresentationUtil.getEditorTabTitle(EditorTabPresentationUtil.java:19)
	at com.intellij.openapi.vfs.newvfs.VfsPresentationUtil.getPresentableNameForUI(VfsPresentationUtil.java:28)
	at com.intellij.ide.actions.SearchEverywherePsiRenderer.getElementText(SearchEverywherePsiRenderer.java:66)
	at com.intellij.ide.util.PsiElementListCellRenderer$1.getPresentableText(PsiElementListCellRenderer.java:416)
	at com.intellij.ide.util.PsiElementListCellRenderer.targetPresentation(PsiElementListCellRenderer.java:449)
	at com.intellij.ide.util.PsiElementListCellRenderer.computePresentation(PsiElementListCellRenderer.java:398)
	at com.intellij.ide.actions.searcheverywhere.PSIPresentationBgRendererWrapper.lambda$createCalculator$1(PSIPresentationBgRendererWrapper.java:75)
	at com.intellij.ide.actions.searcheverywhere.PSIPresentationBgRendererWrapper.element2presentation(PSIPresentationBgRendererWrapper.java:88)
	at com.intellij.ide.actions.searcheverywhere.PSIPresentationBgRendererWrapper.lambda$fetchWeightedElements$0(PSIPresentationBgRendererWrapper.java:68)
	at com.intellij.ide.actions.searcheverywhere.FileSearchEverywhereContributor.processElement(FileSearchEverywhereContributor.java:110)
	at com.intellij.ide.actions.searcheverywhere.AbstractGotoSEContributor.lambda$fetchWeightedElements$1(AbstractGotoSEContributor.java:245)
	at com.intellij.ide.actions.GotoFileItemProvider$SuffixMatches.lambda$processFiles$4(GotoFileItemProvider.java:423)
	at com.intellij.util.containers.ContainerUtil.process(ContainerUtil.java:702)
	at com.intellij.ide.actions.GotoFileItemProvider$SuffixMatches.processFiles(GotoFileItemProvider.java:425)
	at com.intellij.ide.actions.GotoFileItemProvider.processItemsForPattern(GotoFileItemProvider.java:109)
	at com.intellij.ide.actions.GotoFileItemProvider.doFilterElements(GotoFileItemProvider.java:81)
	at com.intellij.ide.actions.GotoFileItemProvider.lambda$filterElementsWithWeights$0(GotoFileItemProvider.java:62)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.actions.GotoFileItemProvider.filterElementsWithWeights(GotoFileItemProvider.java:62)
	at com.intellij.ide.actions.searcheverywhere.AbstractGotoSEContributor.lambda$fetchWeightedElements$4(AbstractGotoSEContributor.java:244)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1111)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:71)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:128)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:109)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:68)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:68)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:106)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:71)
	at com.intellij.ide.actions.searcheverywhere.AbstractGotoSEContributor.fetchWeightedElements(AbstractGotoSEContributor.java:270)
	at com.intellij.ide.actions.searcheverywhere.PSIPresentationBgRendererWrapper.fetchWeightedElements(PSIPresentationBgRendererWrapper.java:67)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ContributorSearchTask.run(MixedResultsSearcher.java:183)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:246)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by trinhanhngoc** [comment]
Hi @sjpatel21 This is an issue of PyCharm itself. You can try [Invalidate Cache ](https://www.jetbrains.com/help/pycharm/cleaning-system-cache.html) to see if it helps.

Like https://github.com/odoo-ide/pycharm-odoo/issues/326.
