### ISSUE TITLE
java.lang.ClassCastException in RngNsDescriptor.init

### ISSUE THREAD

**Issue by fotisp** [trinhanhngoc/pycharm-odoo#404]
Hello,

The plugin stops working at random moments.

This is the IntelliJ version.
```
IntelliJ IDEA 2023.2 (Ultimate Edition)
Build #IU-232.8660.185, built on July 26, 2023
Licensed to Fotis Paraskevopoulos
Subscription is active until October 8, 2023.
For educational use only.
Runtime version: 17.0.7+7-b1000.6 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 10240M
Cores: 16
Metal Rendering is ON
Registry:
    scala.erase.compiler.process.jdk.once=false
    js.debugger.use.node.options=false

Non-Bundled Plugins:
    com.jetbrains.plugins.ini4idea (232.8660.205)
    me.laria.code.idea_caseconv (0.7.1)
    ideanginx9 (0.1.9)
    net.sjrx.intellij.plugins.systemdunitfiles (223.230322.126)
    com.intellij.apacheConfig (232.8660.205)
    com.mle.idea.sbtexecutor (1.4.1)
    org.jetbrains.plugins.localization (232.8660.88)
    org.jetbrains.plugins.rest (232.8660.88)
    String Manipulation (9.10.0)
    me.serce.solidity (2.4.2)
    Pythonid (232.8660.185)
    R4Intellij (232.8660.142)
    net.seesharpsoft.intellij.plugins.csv (3.2.1-232)
    dev.ngocta.pycharm-odoo (2023.7.1.232)
    com.haulmont.jpab (2023.3.1-232)
    org.intellij.scala (2023.2.17)
    com.jetbrains.php (232.8660.205)
    com.jetbrains.twig (232.8660.205)
    com.tjhelmuth.postgres-explain-visualizer (0.9)

Kotlin: 232-1.9.0-IJ8660.185
```

This is the exception
```
  java.lang.ClassCastException: class com.jetbrains.django.lang.template.psi.impl.DjangoTemplateFileImpl cannot be cast to class com.intellij.psi.xml.XmlFile (com.jetbrains.django.lang.template.psi.impl.DjangoTemplateFileImpl is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @3d8660b6; com.intellij.psi.xml.XmlFile is in unnamed module of loader com.intellij.util.lang.PathClassLoader @5fe5c6f)
at org.intellij.plugins.relaxNG.model.descriptors.RngNsDescriptor.init(RngNsDescriptor.java:245)
at dev.ngocta.pycharm.odoo.xml.OdooXmlUtils.getRngNSDescriptor(OdooXmlUtils.java:330)
at dev.ngocta.pycharm.odoo.xml.OdooXmlElementDescriptorProvider.getDescriptor(OdooXmlElementDescriptorProvider.java:25)
at com.intellij.psi.impl.source.xml.XmlTagDelegate.computeElementDescriptor(XmlTagDelegate.java:465)
at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:110)
at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:65)
at com.intellij.psi.impl.source.xml.XmlTagDelegate$1.compute(XmlTagDelegate.java:444)
at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:37)
at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:240)
at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:240)
at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:110)
at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:65)
at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:27)
at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:69)
at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
at com.intellij.psi.impl.source.xml.XmlTagDelegate.getDescriptor(XmlTagDelegate.java:440)
at com.intellij.psi.impl.source.xml.XmlTagImpl.getDescriptor(XmlTagImpl.java:120)
at com.intellij.xml.util.XmlEnumeratedValueReferenceProvider$1.getDescriptor(XmlEnumeratedValueReferenceProvider.java:92)
at com.intellij.xml.util.XmlEnumeratedValueReferenceProvider$1.getDescriptor(XmlEnumeratedValueReferenceProvider.java:88)
at com.intellij.xml.util.XmlEnumeratedValueReferenceProvider.getReferencesByElement(XmlEnumeratedValueReferenceProvider.java:63)
at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getReferences(ReferenceProvidersRegistryImpl.java:182)
at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.mapNotEmptyReferencesFromProviders(ReferenceProvidersRegistryImpl.java:163)
at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:142)
at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.lambda$getReferencesFromProviders$0(ReferenceProvidersRegistry.java:45)
at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:37)
at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:240)
at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:240)
at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:110)
at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:65)
at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:27)
at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:69)
at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:43)
at com.intellij.psi.impl.source.xml.XmlTagDelegate.getReferencesImpl(XmlTagDelegate.java:164)
at com.intellij.psi.impl.source.xml.XmlTagDelegate.lambda$getDefaultReferences$0(XmlTagDelegate.java:125)
at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:37)
at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:240)
at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:240)
at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:110)
at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:65)
at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:27)
at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:69)
at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
at com.intellij.psi.impl.source.xml.XmlTagDelegate.getDefaultReferences(XmlTagDelegate.java:125)
at com.intellij.psi.impl.source.xml.XmlTagImpl.getReferences(XmlTagImpl.java:88)
at com.intellij.psi.impl.source.xml.XmlTagImpl.getReferences(XmlTagImpl.java:78)
at com.intellij.codeInsight.daemon.impl.analysis.XmlNsPrefixAnnotator.annotate(XmlNsPrefixAnnotator.java:44)
at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:130)
at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:107)
at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:360)
at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$7(GeneralHighlightingPass.java:291)
at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:320)
at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:323)
at com.intellij.codeInsight.daemon.impl.analysis.XmlHighlightVisitor.analyze(XmlHighlightVisitor.java:584)
at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:323)
at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:323)
at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:92)
at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:323)
at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:323)
at com.intellij.lang.javascript.validation.JSSemanticKeywordHighlighter.analyze(JSSemanticKeywordHighlighter.java:65)
at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:323)
at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:286)
at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:234)
at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:95)
at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:390)
at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:77)
at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:24)
at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:386)
at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1133)
at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:377)
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:376)
at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:352)
at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:201)
at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:207)
at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:350)
at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:185)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

The plugin version

```
Version 2023.7.1
```

We are on the paid version

**Comment by trinhanhngoc** [comment]
Hello @fotisp . Thank you for the bug report. This issue will be fixed in the next version released next week.

**Comment by trinhanhngoc** [comment]
Hello @fotisp . The new version 2023.8.0 just released with the fix for this issue.

**Comment by fotisp** [comment]
Thank you @trinhanhngoc
