### ISSUE TITLE
EAP2024.1 startup crash

### ISSUE THREAD

**Issue by PNurm** [trinhanhngoc/pycharm-odoo#456]
java.lang.NoSuchMethodError: 'com.intellij.openapi.components.ComponentManager com.intellij.openapi.extensions.impl.ExtensionPointImpl.getComponentManager()'
    at dev.ngocta.pycharm.odoo.OdooApplicationInitializedListener.adjustCompletionContributor(OdooApplicationInitializedListener.java:21)
    at dev.ngocta.pycharm.odoo.OdooApplicationInitializedListener.componentsInitialized(OdooApplicationInitializedListener.java:14)
    at com.intellij.ide.ApplicationInitializedListener$execute$2.invoke(ApplicationInitializedListener.kt:36)
    at com.intellij.ide.ApplicationInitializedListener$execute$2.invoke(ApplicationInitializedListener.kt:34)
    at com.intellij.openapi.progress.CoroutinesKt.blockingContextInner(coroutines.kt:320)
    at com.intellij.openapi.progress.CoroutinesKt.access$blockingContextInner(coroutines.kt:1)
    at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invokeSuspend(coroutines.kt:197)
    at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
    at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
    at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
    at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
    at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:196)
    at com.intellij.ide.ApplicationInitializedListener.execute$suspendImpl(ApplicationInitializedListener.kt:34)
    at com.intellij.ide.ApplicationInitializedListener.execute(ApplicationInitializedListener.kt)
    at com.intellij.platform.ide.bootstrap.ApplicationLoader$callAppInitialized$1.invokeSuspend(ApplicationLoader.kt:495)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

-----
Your JRE: 21.0.2+13-b346.3 amd64 (JetBrains s.r.o.)
/snap/intellij-idea-ultimate/475/jbr

**Comment by trinhanhngoc** [comment]
Like #455

**Comment by trinhanhngoc** [comment]
Hello @PNurm ,

The new version 2024.1.2 has been released with support for PyCharm 2024.1.
