### ISSUE TITLE
java.lang.IllegalArgumentException: recordId is not yet allocated

### ISSUE THREAD

**Issue by jerzyk** [trinhanhngoc/pycharm-odoo#457]
```
java.lang.IllegalArgumentException: recordId(4194391) is not yet allocated: allocated ids are all < 4187453
	at com.intellij.openapi.vfs.newvfs.persistent.dev.blobstorage.StreamlinedBlobStorageHelper.checkRecordIdExists(StreamlinedBlobStorageHelper.java:398)
	at com.intellij.openapi.vfs.newvfs.persistent.dev.blobstorage.StreamlinedBlobStorageOverMMappedFile.readRecord(StreamlinedBlobStorageOverMMappedFile.java:200)
	at com.intellij.openapi.vfs.newvfs.persistent.dev.blobstorage.StreamlinedBlobStorageHelper.readRecord(StreamlinedBlobStorageHelper.java:216)
	at com.intellij.openapi.vfs.newvfs.persistent.AttributesStorageOverBlobStorage.readAttributeValue(AttributesStorageOverBlobStorage.java:1026)
	at com.intellij.openapi.vfs.newvfs.persistent.AttributesStorageOverBlobStorage.readAttributeRaw(AttributesStorageOverBlobStorage.java:134)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSAttributeAccessor.readAttributeRaw(PersistentFSAttributeAccessor.java:72)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSTreeRawAccessor.mayHaveChildren(PersistentFSTreeRawAccessor.java:118)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecordsImpl.mayHaveChildren(FSRecordsImpl.java:662)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.mayHaveChildren(PersistentFSImpl.java:2322)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findInPersistence(VirtualDirectoryImpl.java:172)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.doFindChild(VirtualDirectoryImpl.java:137)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:83)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.doFindChildById(VirtualDirectoryImpl.java:563)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl$ParentFinder.findChild(PersistentFSImpl.java:1853)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl$ParentFinder.findDescendantByIdPath(PersistentFSImpl.java:1841)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl$ParentFinder.find(PersistentFSImpl.java:1929)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findFileById(PersistentFSImpl.java:1670)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findFileById(PersistentFSImpl.java:76)
	at com.intellij.openapi.vfs.PlatformVirtualFileManager.findFileById(PlatformVirtualFileManager.java:52)
	at com.intellij.openapi.vfs.CompactVirtualFileSet$2.next(CompactVirtualFileSet.java:399)
	at com.intellij.openapi.vfs.CompactVirtualFileSet$2.next(CompactVirtualFileSet.java:388)
	at com.intellij.util.containers.SequenceIterator.next(SequenceIterator.java:39)
	at com.intellij.openapi.vfs.CompactVirtualFileSet$3.findNext(CompactVirtualFileSet.java:425)
	at com.intellij.openapi.vfs.CompactVirtualFileSet$3.hasNext(CompactVirtualFileSet.java:416)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1855)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:292)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:298)
	at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at com.intellij.util.containers.ContainerUtil.newHashSet(ContainerUtil.java:292)
	at com.intellij.util.indexing.FileBasedIndexEx.getContainingFiles(FileBasedIndexEx.java:220)
	at com.intellij.util.indexing.FileBasedIndexImpl.getContainingFiles(FileBasedIndexImpl.java:1073)
	at dev.ngocta.pycharm.odoo.module.OdooModuleIndex.getModuleByName(OdooModuleIndex.java:57)
	at dev.ngocta.pycharm.odoo.module.OdooModuleIndex.getModuleByName(OdooModuleIndex.java:70)
	at dev.ngocta.pycharm.odoo.module.OdooModule.lambda$getDepends$0(OdooModule.java:73)
	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValue(OdooUtils.java:355)
	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValue(OdooUtils.java:366)
	at dev.ngocta.pycharm.odoo.OdooUtils.getCachedValue(OdooUtils.java:339)
	at dev.ngocta.pycharm.odoo.module.OdooModule.getDepends(OdooModule.java:62)
	at dev.ngocta.pycharm.odoo.module.OdooModule.lambda$getModuleWithRecursiveDepends$2(OdooModule.java:101)
	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValue(OdooUtils.java:355)
	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValue(OdooUtils.java:366)
	at dev.ngocta.pycharm.odoo.OdooUtils.getCachedValue(OdooUtils.java:339)
	at dev.ngocta.pycharm.odoo.module.OdooModule.getModuleWithRecursiveDepends(OdooModule.java:90)
	at dev.ngocta.pycharm.odoo.module.OdooModule.lambda$getModuleScope$7(OdooModule.java:227)
	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValue(OdooUtils.java:355)
	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValue(OdooUtils.java:366)
	at dev.ngocta.pycharm.odoo.module.OdooModule.getModuleScope(OdooModule.java:223)
	at dev.ngocta.pycharm.odoo.module.OdooModule.getModuleWithDependenciesScope(OdooModule.java:202)
	at dev.ngocta.pycharm.odoo.data.OdooExternalIdIndex.findRecordsById(OdooExternalIdIndex.java:243)
	at dev.ngocta.pycharm.odoo.xml.dom.OdooDomViewElement.getInheritedViewArch(OdooDomViewElement.java:173)
	at dev.ngocta.pycharm.odoo.xml.dom.OdooDomViewElement.lambda$locateInheritedElement$0(OdooDomViewElement.java:229)
	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValue(OdooUtils.java:355)
	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValue(OdooUtils.java:366)
	at dev.ngocta.pycharm.odoo.OdooUtils.getCachedValue(OdooUtils.java:339)
	at dev.ngocta.pycharm.odoo.xml.dom.OdooDomViewElement.locateInheritedElement(OdooDomViewElement.java:224)
	at dev.ngocta.pycharm.odoo.xml.descriptor.OdooViewInheritLocatorElementDescriptor.<init>(OdooViewInheritLocatorElementDescriptor.java:25)
	at dev.ngocta.pycharm.odoo.xml.descriptor.OdooRngElementDescriptor.getElementDescriptor(OdooRngElementDescriptor.java:62)
	at dev.ngocta.pycharm.odoo.xml.descriptor.OdooXmlElementDescriptorProvider.getDescriptor(OdooXmlElementDescriptorProvider.java:23)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.computeElementDescriptor(XmlTagDelegate.java:455)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate$1.compute(XmlTagDelegate.java:436)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:37)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:240)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:27)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:69)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.getDescriptor(XmlTagDelegate.java:432)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.getDescriptor(XmlTagImpl.java:120)
	at dev.ngocta.pycharm.odoo.xml.descriptor.OdooXmlElementDescriptorProvider.getDescriptor(OdooXmlElementDescriptorProvider.java:21)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.computeElementDescriptor(XmlTagDelegate.java:455)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate$1.compute(XmlTagDelegate.java:436)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:37)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:240)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:27)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:69)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at com.intellij.psi.impl.source.xml.XmlTagDelegate.getDescriptor(XmlTagDelegate.java:432)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.getDescriptor(XmlTagImpl.java:120)
	at com.intellij.psi.impl.source.xml.XmlAttributeDelegate.getDescriptionImpl(XmlAttributeDelegate.java:64)
	at com.intellij.psi.impl.source.xml.XmlAttributeDelegate.lambda$getDescriptor$0(XmlAttributeDelegate.java:54)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:37)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:240)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:27)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:69)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at com.intellij.psi.impl.source.xml.XmlAttributeDelegate.getDescriptor(XmlAttributeDelegate.java:52)
	at com.intellij.psi.impl.source.xml.XmlAttributeImpl.getDescriptor(XmlAttributeImpl.java:179)
	at com.intellij.xml.util.XmlEnumeratedValueReferenceProvider.getDescriptor(XmlEnumeratedValueReferenceProvider.java:71)
	at com.intellij.xml.util.XmlEnumeratedValueReferenceProvider.getReferencesByElement(XmlEnumeratedValueReferenceProvider.java:44)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getReferences(ReferenceProvidersRegistryImpl.java:184)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.mapNotEmptyReferencesFromProviders(ReferenceProvidersRegistryImpl.java:165)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:144)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:51)
	at com.intellij.psi.impl.source.xml.XmlAttributeValueImpl.getReferences(XmlAttributeValueImpl.java:80)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.addReferences(SharedPsiElementImplUtil.java:56)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.findReferenceAt(SharedPsiElementImplUtil.java:33)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.findReferenceAt(SharedPsiElementImplUtil.java:50)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.findReferenceAt(CompositePsiElement.java:102)
	at com.intellij.psi.AbstractFileViewProvider.findReferenceAt(AbstractFileViewProvider.java:226)
	at com.intellij.psi.SingleRootFileViewProvider.findReferenceAt(SingleRootFileViewProvider.java:222)
	at com.intellij.psi.impl.source.PsiFileImpl.findReferenceAt(PsiFileImpl.java:525)
	at com.intellij.codeInsight.TargetElementUtilBase.findReference(TargetElementUtilBase.java:189)
	at com.intellij.codeInsight.TargetElementUtilBase.doGetReferenceOrReferencedElement(TargetElementUtilBase.java:156)
	at com.intellij.codeInsight.TargetElementUtilBase.getReferenceOrReferencedElement(TargetElementUtilBase.java:203)
	at com.intellij.codeInsight.TargetElementUtilBase.getReferencedElement(TargetElementUtilBase.java:245)
	at com.intellij.codeInsight.TargetElementUtilBase.doFindTargetElement(TargetElementUtilBase.java:225)
	at com.intellij.codeInsight.TargetElementUtilBase.findTargetElement(TargetElementUtilBase.java:287)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:147)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorPsiDataProvider.getPsiElementIn(TextEditorPsiDataProvider.java:221)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorPsiDataProvider.getSlowData(TextEditorPsiDataProvider.java:131)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorPsiDataProvider.lambda$getData$0(TextEditorPsiDataProvider.java:58)
	at com.intellij.ide.impl.DataManagerImpl.getDataFromProviderInner(DataManagerImpl.java:242)
	at com.intellij.ide.impl.DataManagerImpl.getSlowData(DataManagerImpl.java:226)
	at com.intellij.ide.impl.DataManagerImpl.lambda$getDataRuleInner$6(DataManagerImpl.java:178)
	at com.intellij.ide.impl.DataManagerImpl.lambda$getDataRuleInner$8(DataManagerImpl.java:183)
	at com.intellij.ide.impl.DataManagerImpl.getDataFromRuleInner(DataManagerImpl.java:113)
	at com.intellij.ide.impl.DataManagerImpl.getDataFromRulesInner(DataManagerImpl.java:100)
	at com.intellij.ide.impl.DataManagerImpl.getDataFromProviderAndRulesInner(DataManagerImpl.java:86)
	at com.intellij.ide.impl.DataManagerImpl.lambda$getDataFromRuleInner$3(DataManagerImpl.java:114)
	at com.intellij.openapi.actionSystem.DataKey.getData(DataKey.java:73)
	at com.intellij.ide.impl.dataRules.NavigatableRule.getData(NavigatableRule.java:24)
	at com.intellij.ide.impl.DataManagerImpl.getRulesData(DataManagerImpl.java:211)
	at com.intellij.ide.impl.DataManagerImpl.lambda$getDataRuleInner$8(DataManagerImpl.java:184)
	at com.intellij.ide.impl.DataManagerImpl.getDataFromRuleInner(DataManagerImpl.java:113)
	at com.intellij.ide.impl.DataManagerImpl.getDataFromRulesInner(DataManagerImpl.java:100)
	at com.intellij.ide.impl.DataManagerImpl.getDataFromProviderAndRulesInner(DataManagerImpl.java:86)
	at com.intellij.ide.impl.DataManagerImpl.lambda$getDataFromRuleInner$3(DataManagerImpl.java:114)
	at com.intellij.openapi.actionSystem.DataKey.getData(DataKey.java:73)
	at com.intellij.ide.impl.dataRules.NavigatableArrayRule.getData(NavigatableArrayRule.java:26)
	at com.intellij.ide.impl.DataManagerImpl.getRulesData(DataManagerImpl.java:211)
	at com.intellij.ide.impl.DataManagerImpl.lambda$getDataRuleInner$8(DataManagerImpl.java:184)
	at com.intellij.ide.impl.DataManagerImpl.getDataFromRuleInner(DataManagerImpl.java:113)
	at com.intellij.ide.impl.DataManagerImpl.getDataFromRulesInner(DataManagerImpl.java:100)
	at com.intellij.ide.impl.DataManagerImpl.getDataFromRules(DataManagerImpl.java:68)
	at com.intellij.openapi.actionSystem.impl.PreCachedDataContext.getDataInner(PreCachedDataContext.java:232)
	at com.intellij.openapi.actionSystem.impl.PreCachedDataContext.getData(PreCachedDataContext.java:174)
	at com.intellij.openapi.actionSystem.DataContext.getData(DataContext.java:57)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.precacheSlowDataKeys(ActionUpdater.kt:296)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.access$precacheSlowDataKeys(ActionUpdater.kt:71)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$ensureSlowDataKeysPreCached$2$1.invoke(ActionUpdater.kt:285)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$ensureSlowDataKeysPreCached$2$1.invoke(ActionUpdater.kt:284)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:108)
	at com.intellij.openapi.application.rw.InternalReadAction.access$insideReadAction(InternalReadAction.kt:16)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:95)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:94)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke$lambda$1$lambda$0(cancellableReadAction.kt:38)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1075)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke$lambda$1(cancellableReadAction.kt:36)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:73)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:128)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke(cancellableReadAction.kt:34)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContextInner(coroutines.kt:321)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:310)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:31)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:94)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:78)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:65)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:16)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$3.invokeSuspend(InternalReadAction.kt:36)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$3.invoke(InternalReadAction.kt)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$3.invoke(InternalReadAction.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at com.intellij.openapi.application.rw.InternalReadAction.runReadAction(InternalReadAction.kt:35)
	at com.intellij.openapi.application.rw.PlatformReadWriteActionSupport.executeReadAction(PlatformReadWriteActionSupport.kt:38)
	at com.intellij.openapi.application.ReadWriteActionSupport.executeReadAction$default(ReadWriteActionSupport.kt:15)
	at com.intellij.openapi.application.CoroutinesKt.constrainedReadActionUndispatched(coroutines.kt:82)
	at com.intellij.openapi.application.CoroutinesKt.readActionUndispatched(coroutines.kt:69)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$ensureSlowDataKeysPreCached$2.invokeSuspend(ActionUpdater.kt:733)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$ensureSlowDataKeysPreCached$2.invoke(ActionUpdater.kt)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$ensureSlowDataKeysPreCached$2.invoke(ActionUpdater.kt)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$getSessionDataDeferred$2$1.invokeSuspend(ActionUpdater.kt:553)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

```

**Comment by trinhanhngoc** [comment]
Hello @jerzyk ,

This is an internal PyCharm issue, and unfortunately, I cannot do anything to resolve it.
