### ISSUE TITLE
com.intellij.util.io.CorruptedException

### ISSUE THREAD

**Issue by sjpatel21** [trinhanhngoc/pycharm-odoo#469]
Getting Error in plugin version: 2024.2.2.233

```
com.intellij.util.io.CorruptedException: Storage corrupted /home/osi/.cache/JetBrains/PyCharm2023.3/index/odoo.decimal.precision/odoo.decimal.precision.storage_i
	at com.intellij.util.io.IntToIntBtree$BtreeIndexNodeView.locate(IntToIntBtree.java:911)
	at com.intellij.util.io.IntToIntBtree$BtreeIndexNodeView.access$100(IntToIntBtree.java:308)
	at com.intellij.util.io.IntToIntBtree.get(IntToIntBtree.java:177)
	at com.intellij.util.io.PersistentBTreeEnumerator.enumerateImpl(PersistentBTreeEnumerator.java:584)
	at com.intellij.util.io.PersistentEnumeratorBase.lambda$doEnumerate$0(PersistentEnumeratorBase.java:266)
	at com.intellij.util.io.PersistentEnumeratorBase.catchCorruption(PersistentEnumeratorBase.java:654)
	at com.intellij.util.io.PersistentEnumeratorBase.doEnumerate(PersistentEnumeratorBase.java:265)
	at com.intellij.util.io.PersistentEnumeratorBase.tryEnumerate(PersistentEnumeratorBase.java:256)
	at com.intellij.util.io.PersistentMapImpl.doGet(PersistentMapImpl.java:655)
	at com.intellij.util.io.PersistentMapImpl.get(PersistentMapImpl.java:613)
	at com.intellij.util.indexing.impl.ValueContainerMap.lambda$getModifiableValueContainer$0(ValueContainerMap.java:81)
	at com.intellij.util.indexing.impl.ChangeTrackingValueContainer.getMergedData(ChangeTrackingValueContainer.java:85)
	at com.intellij.util.indexing.impl.ChangeTrackingValueContainer.getValueIterator(ChangeTrackingValueContainer.java:72)
	at com.intellij.util.indexing.impl.MergedValueContainer$1.<init>(MergedValueContainer.java:26)
	at com.intellij.util.indexing.impl.MergedValueContainer.getValueIterator(MergedValueContainer.java:24)
	at com.intellij.util.indexing.impl.MergedValueContainer.getValueIterator(MergedValueContainer.java:11)
	at com.intellij.util.indexing.FileBasedIndexEx.lambda$processValueIterator$9(FileBasedIndexEx.java:388)
	at com.intellij.util.indexing.FileBasedIndexEx.lambda$processExceptions$6(FileBasedIndexEx.java:302)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:246)
	at com.intellij.util.indexing.FileBasedIndexEx.processExceptions(FileBasedIndexEx.java:302)
	at com.intellij.util.indexing.FileBasedIndexEx.processValueIterator(FileBasedIndexEx.java:391)
	at com.intellij.util.indexing.FileBasedIndexEx.processValuesInScope(FileBasedIndexEx.java:357)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValuesInScope(FileBasedIndexImpl.java:1098)
	at com.intellij.util.indexing.FileBasedIndexEx.processValues(FileBasedIndexEx.java:276)
	at com.intellij.util.indexing.FileBasedIndexEx.processValues(FileBasedIndexEx.java:264)
	at dev.ngocta.pycharm.odoo.data.decimalPrecision.OdooDecimalPrecisionIndex.getDecimalPrecisionByName(OdooDecimalPrecisionIndex.java:117)
	at dev.ngocta.pycharm.odoo.data.decimalPrecision.OdooDecimalPrecisionIndex.getDecimalPrecisionByName(OdooDecimalPrecisionIndex.java:139)
	at dev.ngocta.pycharm.odoo.data.decimalPrecision.OdooDecimalPrecisionReference.doMultiResolve(OdooDecimalPrecisionReference.java:28)
	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValue(OdooUtils.java:360)
	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValueOnModule(OdooUtils.java:387)
	at dev.ngocta.pycharm.odoo.data.decimalPrecision.OdooDecimalPrecisionReference.multiResolve(OdooDecimalPrecisionReference.java:24)
	at com.jetbrains.python.inspections.unresolvedReference.PyUnresolvedReferencesVisitor.processReference(PyUnresolvedReferencesVisitor.java:199)
	at com.jetbrains.python.inspections.unresolvedReference.PyUnresolvedReferencesVisitor.visitPyElement(PyUnresolvedReferencesVisitor.java:143)
	at com.jetbrains.python.psi.PyElementVisitor.visitPyStringLiteralExpression(PyElementVisitor.java:218)
	at com.jetbrains.python.psi.impl.PyStringLiteralExpressionImpl.acceptPyVisitor(PyStringLiteralExpressionImpl.java:43)
	at com.jetbrains.python.psi.impl.PyBaseElementImpl.accept(PyBaseElementImpl.java:61)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$10(InspectionRunner.java:350)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1075)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$11(InspectionRunner.java:379)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:184)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$12(InspectionRunner.java:385)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:158)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:150)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$13(InspectionRunner.java:325)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:129)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:118)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$14(InspectionRunner.java:325)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.lambda$call$0(JobLauncherImpl.java:307)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.call(JobLauncherImpl.java:292)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.call(JobLauncherImpl.java:278)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

```

Another one:

```java.io.IOException: Can't read GistImpl[js.stub.element.gist]{version: 1095485, externalizer: com.intellij.lang.javascript.index.gist.NonCancellableExternalizer@7a1fe81f}
	at com.intellij.util.gist.storage.GistStorageImpl$GistImpl.getProjectData(GistStorageImpl.java:266)
	at com.intellij.util.gist.VirtualFileGistOverGistStorage.getOrCalculateAndCache(VirtualFileGistOverGistStorage.java:66)
	at com.intellij.util.gist.VirtualFileGistOverGistStorage.getUpToDateOrNull(VirtualFileGistOverGistStorage.java:43)
	at com.intellij.lang.javascript.index.gist.JSStubElementGist.lambda$getUpToDateOrNullGistData$3(JSStubElementGist.java:222)
	at com.intellij.lang.javascript.psi.util.SoftlyCachedValue.getOrComputeOnce(SoftlyCachedValue.java:48)
	at com.intellij.lang.javascript.index.gist.JSStubElementGist.getUpToDateOrNullGistData(JSStubElementGist.java:219)
	at com.intellij.lang.javascript.index.gist.JSStubElementGist.getUpToDateOrNullFromGist(JSStubElementGist.java:204)
	at com.intellij.lang.javascript.index.gist.JSStubElementGist.getData(JSStubElementGist.java:139)
	at com.intellij.lang.javascript.index.gist.JSStubElementGist.getData(JSStubElementGist.java:116)
	at com.intellij.lang.javascript.psi.impl.JSCachingTypeOwner.lambda$static$0(JSCachingTypeOwner.java:32)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.doCompute(PsiParameterizedCachedValue.java:31)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:240)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.getValue(PsiParameterizedCachedValue.java:21)
	at com.intellij.psi.util.CachedValuesManager.getParameterizedCachedValue(CachedValuesManager.java:82)
	at com.intellij.lang.javascript.psi.impl.JSStubElementImpl.getCachedValueStubBuildOptimized(JSStubElementImpl.java:364)
	at com.intellij.lang.javascript.psi.impl.JSCachingTypeOwner.getJSType(JSCachingTypeOwner.java:90)
	at com.intellij.lang.javascript.psi.resolve.JSQualifiedNameResolver.lambda$expandElement$2(JSQualifiedNameResolver.java:254)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.lang.javascript.psi.resolve.JSQualifiedNameResolver.expandElement(JSQualifiedNameResolver.java:227)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:174)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.intellij.lang.javascript.psi.resolve.JSQualifiedNameResolver.expandElements(JSQualifiedNameResolver.java:215)
	at com.intellij.lang.javascript.psi.resolve.JSQualifiedNameResolver.getExpandedTopLevelElements(JSQualifiedNameResolver.java:179)
	at com.intellij.lang.javascript.psi.resolve.JSQualifiedNameResolver.resolveByComponents(JSQualifiedNameResolver.java:124)
	at com.intellij.lang.javascript.psi.resolve.JSQualifiedNameResolver.resolveQualifiedName(JSQualifiedNameResolver.java:67)
	at com.intellij.lang.javascript.psi.resolve.JSImportHandler.resolveName(JSImportHandler.java:61)
	at com.intellij.lang.javascript.psi.resolve.JSImportHandler.resolveName(JSImportHandler.java:55)
	at com.intellij.lang.javascript.psi.resolve.JSImportHandler.resolveObjectOrTypeName(JSImportHandler.java:40)
	at dev.ngocta.pycharm.odoo.javascript.OdooJSImportHandler.resolveObjectOrTypeName(OdooJSImportHandler.java:25)
	at com.intellij.lang.javascript.psi.ecma6.impl.ES6ReferenceListImpl.resolveReferenceListMemberNoCache(ES6ReferenceListImpl.java:259)
	at com.intellij.lang.javascript.psi.ecma6.impl.ES6ReferenceListImpl.lambda$static$0(ES6ReferenceListImpl.java:124)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.lang.javascript.psi.ecma6.impl.ES6ReferenceListImpl.lambda$static$1(ES6ReferenceListImpl.java:124)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.doCompute(PsiParameterizedCachedValue.java:31)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:240)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.getValue(PsiParameterizedCachedValue.java:21)
	at com.intellij.psi.util.CachedValuesManager.getParameterizedCachedValue(CachedValuesManager.java:82)
	at com.intellij.lang.javascript.psi.ecma6.impl.ES6ReferenceListImpl.resolveReferenceListMember(ES6ReferenceListImpl.java:251)
	at com.intellij.lang.javascript.psi.ecma6.impl.ES6ReferenceListImpl.resolveMemberClasses(ES6ReferenceListImpl.java:439)
	at com.intellij.lang.javascript.psi.ecma6.impl.JSReferenceListMemberImpl.getClassesWithSubstitutors(JSReferenceListMemberImpl.java:100)
	at com.intellij.lang.javascript.psi.ecma6.impl.ES6ReferenceListImpl.lambda$getReferencedClassesImpl$2(ES6ReferenceListImpl.java:168)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at one.util.streamex.StreamEx.toArray(StreamEx.java:871)
	at com.intellij.lang.javascript.psi.ecma6.impl.ES6ReferenceListImpl.getReferencedClassesImpl(ES6ReferenceListImpl.java:170)
	at com.intellij.lang.javascript.psi.ecmal4.impl.JSReferenceListImpl.getReferencedClasses(JSReferenceListImpl.java:105)
	at com.intellij.lang.javascript.psi.ecmal4.impl.JSClassBase.computeExtendsClasses(JSClassBase.java:509)
	at com.intellij.lang.javascript.psi.ecmal4.impl.JSClassBase$2.computeForScope(JSClassBase.java:536)
	at com.intellij.lang.javascript.psi.ecmal4.impl.JSClassBase$2.computeForScope(JSClassBase.java:532)
	at com.intellij.lang.javascript.psi.resolve.JSInheritanceUtil$CacheByEnforcedResolveScope.compute(JSInheritanceUtil.java:989)
	at com.intellij.lang.javascript.psi.ecmal4.impl.JSClassBase.getClassesFromReferenceList(JSClassBase.java:539)
	at com.intellij.lang.javascript.psi.ecmal4.impl.JSClassBase.getSuperClasses(JSClassBase.java:455)
	at com.intellij.lang.javascript.psi.ecmal4.impl.JSClassBase.getSupers(JSClassBase.java:279)
	at com.intellij.lang.javascript.index.JSTypeEvaluateManager.iterateTypeHierarchyFromJSClasses(JSTypeEvaluateManager.java:146)
	at com.intellij.lang.javascript.index.JSTypeEvaluateManager.iterateTypeHierarchy(JSTypeEvaluateManager.java:116)
	at com.intellij.lang.javascript.psi.resolve.BaseJSSymbolProcessor.addSupers(BaseJSSymbolProcessor.java:245)
	at com.intellij.lang.javascript.psi.resolve.BaseJSSymbolProcessor.<init>(BaseJSSymbolProcessor.java:156)
	at com.intellij.lang.javascript.psi.resolve.WalkUpResolveProcessor.<init>(WalkUpResolveProcessor.java:67)
	at com.intellij.lang.javascript.psi.resolve.JSReferenceExpressionResolver.resolveFromIndices(JSReferenceExpressionResolver.java:325)
	at com.intellij.lang.javascript.psi.resolve.JSReferenceExpressionResolver.doResolveGlobalReference(JSReferenceExpressionResolver.java:255)
	at com.intellij.lang.javascript.psi.resolve.JSReferenceExpressionResolver.resolveGlobalReference(JSReferenceExpressionResolver.java:241)
	at com.intellij.lang.javascript.psi.resolve.JSReferenceExpressionResolver.resolve(JSReferenceExpressionResolver.java:115)
	at com.intellij.lang.javascript.psi.resolve.JSReferenceExpressionResolver.resolve(JSReferenceExpressionResolver.java:47)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil$5.get(JSResolveUtil.java:1673)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil$5.get(JSResolveUtil.java:1670)
	at com.intellij.lang.javascript.psi.resolve.JSEvaluatorComplexityTracker.runTask(JSEvaluatorComplexityTracker.java:67)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard.lambda$getCachedValue$0(JSComplexityAwareRecursionGuard.java:68)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil$4.lambda$calculateWithCaching$0(JSResolveUtil.java:1686)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$5(ResolveCache.java:268)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:234)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:213)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:268)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil$4.calculateWithCaching(JSResolveUtil.java:1684)
	at com.intellij.lang.javascript.psi.resolve.JSComplexityAwareRecursionGuard.getCachedValue(JSComplexityAwareRecursionGuard.java:71)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil.resolve(JSResolveUtil.java:1668)
	at com.intellij.lang.javascript.psi.impl.JSReferenceExpressionImpl.doMultiResolve(JSReferenceExpressionImpl.java:526)
	at com.intellij.lang.javascript.psi.impl.JSReferenceExpressionImpl.multiResolve(JSReferenceExpressionImpl.java:518)
	at com.intellij.lang.javascript.inspections.JSAccessibilityCheckInspection$2.visitJSReferenceExpression(JSAccessibilityCheckInspection.java:54)
	at com.intellij.lang.javascript.psi.impl.JSReferenceExpressionImpl.accept(JSReferenceExpressionImpl.java:506)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$10(InspectionRunner.java:367)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1075)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$11(InspectionRunner.java:379)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:184)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$12(InspectionRunner.java:385)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:158)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:150)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$13(InspectionRunner.java:325)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:129)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:118)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$processInOrder$14(InspectionRunner.java:325)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.lambda$call$0(JobLauncherImpl.java:307)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.call(JobLauncherImpl.java:292)
	at com.intellij.concurrency.JobLauncherImpl$1MyProcessQueueTask.call(JobLauncherImpl.java:278)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.io.IOException: Gist file [/home/osi/.cache/JetBrains/PyCharm2023.3/caches/huge-gists/1711376348802/461101.05459c27-07e5-47b2-9ed6-ca9270d1d433] doesn't exist -> looks like data corruption?
	at com.intellij.util.gist.storage.GistStorageImpl$GistImpl.getProjectData(GistStorageImpl.java:251)
	... 133 more


```

**Comment by trinhanhngoc** [comment]
Hello @sjpatel21 , I am pretty sure these are PyCharm bugs. If these errors occur often, you can try [Invalidate cache](https://www.jetbrains.com/help/pycharm/invalidate-caches.html).
