### ISSUE TITLE
java.lang.IllegalStateException: removeContentEntry: removed content entry url 

### ISSUE THREAD

**Issue by lesdekock** [trinhanhngoc/pycharm-odoo#481]
java.lang.IllegalStateException: removeContentEntry: removed content entry url 'file:///home/<username>/.local/share/JetBrains/PyCharm2024.2/Odoo/stubs/odoo-stubs15' still exists after removing
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.roots.ModifiableRootModelBridgeImpl.removeContentEntry(ModifiableRootModelBridgeImpl.kt:250)
	at dev.ngocta.pycharm.odoo.python.stubs.OdooStubsUpdater.lambda$updateModule$3(OdooStubsUpdater.java:87)
	at com.intellij.openapi.roots.ModuleRootModificationUtil.modifyModel(ModuleRootModificationUtil.java:163)
	at dev.ngocta.pycharm.odoo.python.stubs.OdooStubsUpdater.updateModule(OdooStubsUpdater.java:82)
	at dev.ngocta.pycharm.odoo.python.stubs.OdooStubsUpdater.lambda$updateProject$0(OdooStubsUpdater.java:51)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:249)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:227)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:212)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by trinhanhngoc** [comment]
Hello @lesdekock ,

The same problem was reported in #471. You can find the solution in there.

**Comment by lesdekock** [comment]
All Fixed, Thank you, Les On 21 Aug 2024, at 13:05, Trịnh Anh Ngọc ***@***.***> wrote: Hello @lesdekock , The same problem was reported in #471 . You can find the solution in there. — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you were mentioned. Message ID: ***@***.***>
