### ISSUE TITLE
Error With new Pycharm Version 2024.2.1 (Community Edition)

### ISSUE THREAD

**Issue by IAY-DGTERA** [trinhanhngoc/pycharm-odoo#493]
The plugin stopped working with the new pycharm version PyCharm 2024.2.1 (Community Edition)
Build #PC-242.21829.153, built on August 29, 2024
Runtime version: 21.0.3+13-b509.11 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.X11.XToolkit
Linux 5.4.0-150-generic
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 1926M
Cores: 16
Registry:
  debugger.watches.in.variables=false
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  com.markskelton.one-dark-theme (5.12.0)
  String Manipulation (9.14.1)
  XPathView (242.20224.155)
  GrepConsole (13.1.0-IJ2023.3)
  net.seesharpsoft.intellij.plugins.csv (3.4.0-242)
  dev.ngocta.pycharm-odoo (2024.7.1.242)
  org.jetbrains.plugins.gitlab (242.21829.162)
  zielu.gittoolbox (600.0.0+242)
  mobi.hsz.idea.gitignore (4.5.3)
Current Desktop: ubuntu:GNOME

with the following error
com.intellij.diagnostic.PluginException: Cannot create extension (class=dev.ngocta.pycharm.odoo.rst.OdooRstLanguageInjector) [Plugin: dev.ngocta.pycharm-odoo]
	at com.intellij.serviceContainer.ComponentManagerImpl.createError(ComponentManagerImpl.kt:980)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.doCreateInstance(XmlExtensionAdapter.kt:73)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.kt:33)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.kt:403)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.createExtensionInstances(ExtensionPointImpl.kt:376)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensionList(ExtensionPointImpl.kt:222)
	at com.intellij.openapi.extensions.ProjectExtensionPointName.getExtensions(ProjectExtensionPointName.kt:25)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.calcInjectorMap(InjectedLanguageManagerImpl.java:171)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.getInjectorMap(InjectedLanguageManagerImpl.java:162)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.processInjectableElements(InjectedLanguageManagerImpl.java:148)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.processInjectedPsiFiles(InjectedGeneralHighlightingPass.java:149)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.collectInformationWithProgress(InjectedGeneralHighlightingPass.java:90)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:418)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:118)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:36)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:413)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:291)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:965)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$4(PassExecutorService.java:404)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:403)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:379)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.cacheFileTypesInside(FileTypeManagerImpl.java:802)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$1(PassExecutorService.java:379)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.executeByImpatientReader(AnyThreadWriteThreadingSupport.kt:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:377)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:190)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: com.intellij.diagnostic.PluginException: Cannot create class dev.ngocta.pycharm.odoo.rst.OdooRstLanguageInjector (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Odoo, id=dev.ngocta.pycharm-odoo, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/PyCharmCE2024.2/pycharm-odoo, version=2024.7.1.242, package=null, isBundled=false), packagePrefix=null, state=active, parents=PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.community.deprecated.extensions, descriptorPath=intellij.python.community.deprecated.extensions.xml, path=/snap/pycharm-community/408/plugins/python-ce, version=242.21829.153, package=com.jetbrains.extensions, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.terminal, descriptorPath=intellij.python.terminal.xml, path=/snap/pycharm-community/408/plugins/python-ce, version=242.21829.153, package=com.intellij.python.terminal, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.reStructuredText, descriptorPath=intellij.python.reStructuredText.xml, path=/snap/pycharm-community/408/plugins/python-ce, version=242.21829.153, package=com.intellij.python.reStructuredText, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.markdown, descriptorPath=intellij.python.markdown.xml, path=/snap/pycharm-community/408/plugins/python-ce, version=242.21829.153, package=com.intellij.python.markdown, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.langInjection, descriptorPath=intellij.python.langInjection.xml, path=/snap/pycharm-community/408/plugins/python-ce, version=242.21829.153, package=com.intellij.python.langInjection, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.grazie, descriptorPath=intellij.python.grazie.xml, path=/snap/pycharm-community/408/plugins/python-ce, version=242.21829.153, package=com.intellij.python.grazie, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.featuresTrainer, descriptorPath=intellij.python.featuresTrainer.xml, path=/snap/pycharm-community/408/plugins/python-ce, version=242.21829.153, package=com.intellij.python.featuresTrainer, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.copyright, descriptorPath=intellij.python.copyright.xml, path=/snap/pycharm-community/408/plugins/python-ce, version=242.21829.153, package=com.intellij.python.copyright, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.community.plugin.minorRider, descriptorPath=intellij.python.community.plugin.minorRider.xml, path=/snap/pycharm-community/408/plugins/python-ce, version=242.21829.153, package=com.intellij.python.community.plugin.minorRider, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.community.plugin.minor, descriptorPath=intellij.python.community.plugin.minor.xml, path=/snap/pycharm-community/408/plugins/python-ce, version=242.21829.153, package=com.intellij.python.community.plugin.minor, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.community.plugin.java, descriptorPath=intellij.python.community.plugin.java.xml, path=/snap/pycharm-community/408/plugins/python-ce, version=242.21829.153, package=com.intellij.python.community.plugin.java, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.community.plugin.impl, descriptorPath=intellij.python.community.plugin.impl.xml, path=/snap/pycharm-community/408/plugins/python-ce, version=242.21829.153, package=com.intellij.python.community.plugin.impl, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.community.impl.huggingFace, descriptorPath=intellij.python.community.impl.huggingFace.xml, path=/snap/pycharm-community/408/plugins/python-ce, version=242.21829.153, package=com.intellij.python.community.impl.huggingFace, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.community.communityOnly, descriptorPath=intellij.python.community.communityOnly.xml, path=/snap/pycharm-community/408/plugins/python-ce, version=242.21829.153, package=com.intellij.python.community.communityOnly, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.commandInterface, descriptorPath=intellij.commandInterface.xml, path=/snap/pycharm-community/408/plugins/python-ce, version=242.21829.153, package=com.intellij.commandInterface, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.impl, descriptorPath=intellij.platform.vcs.impl.xml, path=/snap/pycharm-community/408/lib, version=242.21829.153, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.log.impl, descriptorPath=intellij.platform.vcs.log.impl.xml, path=/snap/pycharm-community/408/lib, version=242.21829.153, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.dvcs.impl, descriptorPath=intellij.platform.vcs.dvcs.impl.xml, path=/snap/pycharm-community/408/lib, version=242.21829.153, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.collaborationTools, descriptorPath=intellij.platform.collaborationTools.xml, path=/snap/pycharm-community/408/lib, version=242.21829.153, package=null, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, descriptorPath=plugin.xml, path=/snap/pycharm-community/408/plugins/python-ce, version=242.21829.153, package=com.jetbrains.python, isBundled=true), PluginDescriptor(name=XPathView + XSLT, id=XPathView, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/PyCharmCE2024.2/xpath, version=242.20224.155, package=null, isBundled=false), PluginDescriptor(name=CSV Editor, id=net.seesharpsoft.intellij.plugins.csv, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/PyCharmCE2024.2/CSVEditor, version=3.4.0-242, package=null, isBundled=false), ))
	at com.intellij.serviceContainer.ComponentManagerImpl.doInstantiateClass(ComponentManagerImpl.kt:918)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:894)
	at com.intellij.openapi.extensions.impl.SimpleConstructorInjectionAdapter.instantiateClass(XmlExtensionAdapter.kt:103)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.doCreateInstance(XmlExtensionAdapter.kt:52)
	... 37 more
Caused by: java.lang.RuntimeException: Cannot find suitable constructor, expected (Project), (Project, CoroutineScope), (CoroutineScope), or ()
	at com.intellij.openapi.project.impl.ProjectImpl.findConstructorAndInstantiateClass(ProjectImpl.kt:152)
	at com.intellij.serviceContainer.ComponentManagerImpl.doInstantiateClass(ComponentManagerImpl.kt:909)
	... 40 more

**Comment by trinhanhngoc** [comment]
@IAY-DGTERA ,

Please update to the PyCharm 2024.2.2. Related issue: https://github.com/odoo-ide/pycharm-odoo/issues/489

**Comment by IAY-DGTERA** [comment]
Thanks It's Working Now
