### ISSUE TITLE
Indexing issue related to OdooEditorTabTitleProvider

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#497]
```
com.intellij.diagnostic.PluginException: Parent dir[/home/batman/.cache/JetBrains/PyCharm2024.2/index/fastAttributes] is not exist/was removed -- can't create .lock-file.
First existing parent: [/home/batman/.cache/JetBrains/PyCharm2024.2/index] [Plugin: dev.ngocta.pycharm-odoo]
	at com.intellij.openapi.fileEditor.impl.EditorTabPresentationUtil.getCustomEditorTabTitleAsync(EditorTabPresentationUtil.kt:60)
	at com.intellij.openapi.fileEditor.impl.EditorTabbedContainer$insertTab$3.invokeSuspend(EditorTabbedContainer.kt:240)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
Caused by: java.io.IOException: Parent dir[/home/batman/.cache/JetBrains/PyCharm2024.2/index/fastAttributes] is not exist/was removed -- can't create .lock-file.
First existing parent: [/home/batman/.cache/JetBrains/PyCharm2024.2/index]
	at com.intellij.platform.util.io.storages.mmapped.MMappedFileStorage$RegionAllocationAtomicityLock$FileBasedRegionAllocationLock$RegionImpl.start(MMappedFileStorage.java:716)
	at com.intellij.platform.util.io.storages.mmapped.MMappedFileStorage$Page.ensureFileRegionAllocatedAndZeroed(MMappedFileStorage.java:514)
	at com.intellij.platform.util.io.storages.mmapped.MMappedFileStorage$Page.map(MMappedFileStorage.java:471)
	at com.intellij.platform.util.io.storages.mmapped.MMappedFileStorage$Page.<init>(MMappedFileStorage.java:453)
	at com.intellij.platform.util.io.storages.mmapped.MMappedFileStorage.pageByIndexLocked(MMappedFileStorage.java:422)
	at com.intellij.platform.util.io.storages.mmapped.MMappedFileStorage.pageByIndex(MMappedFileStorage.java:243)
	at com.intellij.platform.util.io.storages.mmapped.MMappedFileStorage.pageByOffset(MMappedFileStorage.java:228)
	at com.intellij.openapi.vfs.newvfs.persistent.mapped.MappedFileStorageHelper.readLongField(MappedFileStorageHelper.java:486)
	at com.intellij.openapi.vfs.newvfs.persistent.SpecializedFileAttributes$FastLongFileAttributeAccessor.read(SpecializedFileAttributes.java:467)
	at com.intellij.util.indexing.impl.perFileVersion.LongFileAttributeImpl.readLong(LongFileAttribute.kt:64)
	at com.intellij.util.indexing.IndexingFlag.isFileChanged(IndexingFlag.kt:122)
	at com.intellij.util.indexing.FileBasedIndexImpl.getIndexingState(FileBasedIndexImpl.java:1996)
	at com.intellij.util.indexing.FileBasedIndexImpl.getIndexingState(FileBasedIndexImpl.java:1989)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$23(FileBasedIndexImpl.java:1479)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.lambda$freezeFileTypeTemporarilyWithProvidedValueIn$15(FileTypeManagerImpl.java:738)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.cacheFileTypesInside(FileTypeManagerImpl.java:802)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyWithProvidedValueIn(FileTypeManagerImpl.java:734)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1457)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1431)
	at com.intellij.util.indexing.FileBasedIndexImpl.processRefreshedFile(FileBasedIndexImpl.java:1374)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1746)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1740)
	at com.intellij.util.indexing.UpdateTask.process(UpdateTask.java:63)
	at com.intellij.util.indexing.UpdateTask.processAll(UpdateTask.java:32)
	at com.intellij.util.indexing.FileBasedIndexImpl.forceUpdate(FileBasedIndexImpl.java:1763)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:846)
	at com.intellij.util.indexing.FileBasedIndexEx.processExceptions(FileBasedIndexEx.java:303)
	at com.intellij.util.indexing.FileBasedIndexEx.getContainingFilesIterator(FileBasedIndexEx.java:250)
	at com.intellij.util.indexing.FileBasedIndexEx.getContainingFiles(FileBasedIndexEx.java:226)
	at com.intellij.util.indexing.FileBasedIndexImpl.getContainingFiles(FileBasedIndexImpl.java:1127)
	at dev.ngocta.pycharm.odoo.OdooEditorTabTitleProvider.lambda$getEditorTabTitle$2(OdooEditorTabTitleProvider.java:52)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction(AnyThreadWriteThreadingSupport.kt:264)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction(AnyThreadWriteThreadingSupport.kt:221)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:857)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:66)
	at dev.ngocta.pycharm.odoo.OdooEditorTabTitleProvider.getEditorTabTitle(OdooEditorTabTitleProvider.java:51)
	at com.intellij.openapi.fileEditor.impl.EditorTabTitleProvider$getEditorTabTitleAsync$2.invoke(EditorTabTitleProvider.kt:29)
	at com.intellij.openapi.fileEditor.impl.EditorTabTitleProvider$getEditorTabTitleAsync$2.invoke(EditorTabTitleProvider.kt:28)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContextInner(coroutines.kt:339)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invokeSuspend(coroutines.kt:232)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:261)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:231)
	at com.intellij.openapi.fileEditor.impl.EditorTabTitleProvider.getEditorTabTitleAsync$suspendImpl(EditorTabTitleProvider.kt:28)
	at com.intellij.openapi.fileEditor.impl.EditorTabTitleProvider.getEditorTabTitleAsync(EditorTabTitleProvider.kt)
	at com.intellij.openapi.fileEditor.impl.EditorTabPresentationUtil.getCustomEditorTabTitleAsync(EditorTabPresentationUtil.kt:54)
	... 7 more
Caused by: java.nio.file.NoSuchFileException: /home/batman/.cache/JetBrains/PyCharm2024.2/index/fastAttributes/.indexing.flag.8388608.lock
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:261)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:379)
	at java.base/java.nio.file.Files.createFile(Files.java:657)
	at com.intellij.platform.util.io.storages.mmapped.MMappedFileStorage$RegionAllocationAtomicityLock$FileBasedRegionAllocationLock$RegionImpl.start(MMappedFileStorage.java:709)
	... 54 more

```

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 ,

The new version this week will addess this issue.

**Comment by trinhanhngoc** [comment]
Hello @jcfernandez-890825 ,

The new version 2024.8.0 has been released with the fix.
