### ISSUE TITLE
StackOverflowError in OdooModelLikeUtils.getModelLikeClassHandler()

### ISSUE THREAD

**Issue by Jerther** [trinhanhngoc/pycharm-odoo#505]
Hi!!

I understandably hit this error after I <ins>mistakenly</ins> pasted an import line for a class that <ins>mistakenly</ins> inherits itself. :wink: 

Version 2024.9.0.242

```python
from odoo import tests
from odoo.addons.my_module.tests.base_template_test import BaseTemplateTest   # <-- Error happened immediately after pasting this line.


class BaseTemplateTest(BaseTemplateTest):
    ...
```

<details>
<summary>Stack Trace</summary>

```
java.lang.StackOverflowError
	at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:336)
	at com.intellij.openapi.progress.ProgressIndicatorProvider.checkCanceled(ProgressIndicatorProvider.java:41)
	at com.intellij.psi.impl.source.tree.CompositeElement.getPsi(CompositeElement.java:693)
	at com.intellij.psi.impl.source.SourceTreeToPsiMap.treeElementToPsi(SourceTreeToPsiMap.java:15)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.getNextSibling(SharedImplUtil.java:45)
	at com.intellij.psi.impl.source.tree.LeafPsiElement.getNextSibling(LeafPsiElement.java:61)
	at com.intellij.psi.util.PsiTreeUtil.getChildOfType(PsiTreeUtil.java:333)
	at com.jetbrains.python.ast.PyAstClass.getSuperClassExpressionList(PyAstClass.java:75)
	at com.jetbrains.python.psi.PyClass.getSuperClassExpressionList(PyClass.java:92)
	at com.jetbrains.python.psi.impl.PyClassImpl.getSuperClassExpressions(PyClassImpl.java:132)
	at dev.ngocta.pycharm.odoo.model.common.OdooModelLikeUtils.lambda$getModelLikeClassHandler$3(OdooModelLikeUtils.java:54)
	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValue(OdooUtils.java:341)
	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValue(OdooUtils.java:352)
	at dev.ngocta.pycharm.odoo.model.common.OdooModelLikeUtils.getModelLikeClassHandler(OdooModelLikeUtils.java:50)
	at dev.ngocta.pycharm.odoo.model.common.OdooModelLikeUtils.lambda$getModelLikeClassHandler$3(OdooModelLikeUtils.java:91)
	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValue(OdooUtils.java:341)
	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValue(OdooUtils.java:352)
	at dev.ngocta.pycharm.odoo.model.common.OdooModelLikeUtils.getModelLikeClassHandler(OdooModelLikeUtils.java:50)
	at dev.ngocta.pycharm.odoo.model.common.OdooModelLikeUtils.lambda$getModelLikeClassHandler$3(OdooModelLikeUtils.java:91)
	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValue(OdooUtils.java:341)
	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValue(OdooUtils.java:352)
	at dev.ngocta.pycharm.odoo.model.common.OdooModelLikeUtils.getModelLikeClassHandler(OdooModelLikeUtils.java:50)
	at dev.ngocta.pycharm.odoo.model.common.OdooModelLikeUtils.lambda$getModelLikeClassHandler$3(OdooModelLikeUtils.java:91)
	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValue(OdooUtils.java:341)
	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValue(OdooUtils.java:352)
	at dev.ngocta.pycharm.odoo.model.common.OdooModelLikeUtils.getModelLikeClassHandler(OdooModelLikeUtils.java:50)
	at dev.ngocta.pycharm.odoo.model.common.OdooModelLikeUtils.lambda$getModelLikeClassHandler$3(OdooModelLikeUtils.java:91)
	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValue(OdooUtils.java:341)
	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValue(OdooUtils.java:352)
	at dev.ngocta.pycharm.odoo.model.common.OdooModelLikeUtils.getModelLikeClassHandler(OdooModelLikeUtils.java:50)
	at dev.ngocta.pycharm.odoo.model.common.OdooModelLikeUtils.lambda$getModelLikeClassHandler$3(OdooModelLikeUtils.java:91)
	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValue(OdooUtils.java:341)
	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValue(OdooUtils.java:352)
...

```

</details>

**Comment by trinhanhngoc** [comment]
Hi @Jerther ,

Thanks for the report. This bug will be fixed in the next version.

**Comment by trinhanhngoc** [comment]
Hello @Jerther ,

The new version 2024.9.1 has been released with the fix.
