### ISSUE TITLE
com.intellij.diagnostic.PluginException: Cannot create extension in PyCharm Community

### ISSUE THREAD

**Issue by Jerther** [trinhanhngoc/pycharm-odoo#510]
Hi!

I've updated the plugin to 2024.9.1.242 and now I get this crash right after launching PyCharm 2024.2.4

```
com.intellij.diagnostic.PluginException: Cannot create extension (class=dev.ngocta.pycharm.odoo.file.OdooFileReferenceProvider) [Plugin: dev.ngocta.pycharm-odoo]
	at com.intellij.serviceContainer.ComponentManagerImpl.createError(ComponentManagerImpl.kt:980)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.doCreateInstance(XmlExtensionAdapter.kt:73)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.kt:33)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.kt:403)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.createExtensionInstances(ExtensionPointImpl.kt:376)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensionList(ExtensionPointImpl.kt:222)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensionList(ExtensionPointName.kt:54)
	at dev.ngocta.pycharm.odoo.symbol.OdooSymbolReferenceContributor$1.getReferencesByElement(OdooSymbolReferenceContributor.java:22)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getReferences(ReferenceProvidersRegistryImpl.java:162)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.mapNotEmptyReferencesFromProviders(ReferenceProvidersRegistryImpl.java:143)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:122)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:51)
	at com.intellij.psi.PsiReferenceServiceImpl.doGetReferences(PsiReferenceServiceImpl.java:32)
	at com.intellij.psi.PsiReferenceServiceImpl.getReferences(PsiReferenceServiceImpl.java:25)
	at com.intellij.codeInsight.highlighting.HyperlinkAnnotator.lambda$static$0(HyperlinkAnnotator.java:82)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.doCompute(PsiParameterizedCachedValue.kt:23)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:236)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:236)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:237)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.getValue(PsiParameterizedCachedValue.kt:17)
	at com.intellij.psi.util.CachedValuesManager.getParameterizedCachedValue(CachedValuesManager.java:97)
	at com.intellij.codeInsight.highlighting.HyperlinkAnnotator.getReferences(HyperlinkAnnotator.java:94)
	at com.intellij.codeInsight.highlighting.HyperlinkAnnotator.annotateContributedReferences(HyperlinkAnnotator.java:64)
	at com.intellij.codeInsight.highlighting.HyperlinkAnnotator.annotate(HyperlinkAnnotator.java:59)
	at com.intellij.codeInsight.daemon.impl.AnnotationHolderImpl.runAnnotatorWithContext(AnnotationHolderImpl.java:216)
	at com.intellij.codeInsight.daemon.impl.AnnotatorRunner.lambda$runAnnotator$2(AnnotatorRunner.java:129)
	at com.intellij.codeInsight.daemon.impl.AnnotationSessionImpl.computeWithSession(AnnotationSessionImpl.java:87)
	at com.intellij.codeInsight.daemon.impl.AnnotatorRunner.runAnnotator(AnnotatorRunner.java:119)
	at com.intellij.codeInsight.daemon.impl.AnnotatorRunner.lambda$runAnnotatorsAsync$0(AnnotatorRunner.java:66)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:279)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:965)
	at com.intellij.codeInsight.daemon.impl.AnnotatorRunner.lambda$runAnnotatorsAsync$1(AnnotatorRunner.java:66)
	at com.intellij.concurrency.ApplierCompleter.processArrayItem(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.processArray(ApplierCompleter.java:196)
	at com.intellij.concurrency.ApplierCompleter.execAll(ApplierCompleter.java:166)
	at com.intellij.concurrency.ApplierCompleter.lambda$exec$0(ApplierCompleter.java:105)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:291)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:965)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$2(ApplierCompleter.java:148)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:159)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapAndRun$1(ApplierCompleter.java:140)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.executeByImpatientReader(AnyThreadWriteThreadingSupport.kt:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.concurrency.ApplierCompleter.wrapAndRun(ApplierCompleter.java:140)
	at com.intellij.concurrency.ApplierCompleter.exec(ApplierCompleter.java:108)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: com.intellij.diagnostic.PluginException: Cannot create class dev.ngocta.pycharm.odoo.file.OdooFileReferenceProvider (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Odoo, id=dev.ngocta.pycharm-odoo, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/PyCharmCE2024.2/pycharm-odoo, version=2024.9.1.242, package=null, isBundled=false), packagePrefix=null, state=active, parents=PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.community.deprecated.extensions, descriptorPath=intellij.python.community.deprecated.extensions.xml, path=~/Apps/pycharm/plugins/python-ce, version=242.23726.102, package=com.jetbrains.extensions, isBundled=true), PluginDescriptor(name=ReStructuredText, id=org.jetbrains.plugins.rest, moduleName=intellij.restructuredtext.python, descriptorPath=intellij.restructuredtext.python.xml, path=~/Apps/pycharm/plugins/restructuredtext, version=242.23726.102, package=com.intellij.restructuredtext.python, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.terminal, descriptorPath=intellij.python.terminal.xml, path=~/Apps/pycharm/plugins/python-ce, version=242.23726.102, package=com.intellij.python.terminal, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.markdown, descriptorPath=intellij.python.markdown.xml, path=~/Apps/pycharm/plugins/python-ce, version=242.23726.102, package=com.intellij.python.markdown, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.langInjection, descriptorPath=intellij.python.langInjection.xml, path=~/Apps/pycharm/plugins/python-ce, version=242.23726.102, package=com.intellij.python.langInjection, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.grazie, descriptorPath=intellij.python.grazie.xml, path=~/Apps/pycharm/plugins/python-ce, version=242.23726.102, package=com.intellij.python.grazie, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.featuresTrainer, descriptorPath=intellij.python.featuresTrainer.xml, path=~/Apps/pycharm/plugins/python-ce, version=242.23726.102, package=com.intellij.python.featuresTrainer, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.copyright, descriptorPath=intellij.python.copyright.xml, path=~/Apps/pycharm/plugins/python-ce, version=242.23726.102, package=com.intellij.python.copyright, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.community.plugin.minorRider, descriptorPath=intellij.python.community.plugin.minorRider.xml, path=~/Apps/pycharm/plugins/python-ce, version=242.23726.102, package=com.intellij.python.community.plugin.minorRider, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.community.plugin.minor, descriptorPath=intellij.python.community.plugin.minor.xml, path=~/Apps/pycharm/plugins/python-ce, version=242.23726.102, package=com.intellij.python.community.plugin.minor, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.community.plugin.java, descriptorPath=intellij.python.community.plugin.java.xml, path=~/Apps/pycharm/plugins/python-ce, version=242.23726.102, package=com.intellij.python.community.plugin.java, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.community.plugin.impl, descriptorPath=intellij.python.community.plugin.impl.xml, path=~/Apps/pycharm/plugins/python-ce, version=242.23726.102, package=com.intellij.python.community.plugin.impl, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.community.impl.huggingFace, descriptorPath=intellij.python.community.impl.huggingFace.xml, path=~/Apps/pycharm/plugins/python-ce, version=242.23726.102, package=com.intellij.python.community.impl.huggingFace, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.community.communityOnly, descriptorPath=intellij.python.community.communityOnly.xml, path=~/Apps/pycharm/plugins/python-ce, version=242.23726.102, package=com.intellij.python.community.communityOnly, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.commandInterface, descriptorPath=intellij.commandInterface.xml, path=~/Apps/pycharm/plugins/python-ce, version=242.23726.102, package=com.intellij.commandInterface, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.impl, descriptorPath=intellij.platform.vcs.impl.xml, path=~/Apps/pycharm/lib, version=242.23726.102, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.log.impl, descriptorPath=intellij.platform.vcs.log.impl.xml, path=~/Apps/pycharm/lib, version=242.23726.102, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.dvcs.impl, descriptorPath=intellij.platform.vcs.dvcs.impl.xml, path=~/Apps/pycharm/lib, version=242.23726.102, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.collaborationTools, descriptorPath=intellij.platform.collaborationTools.xml, path=~/Apps/pycharm/lib, version=242.23726.102, package=null, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, descriptorPath=plugin.xml, path=~/Apps/pycharm/plugins/python-ce, version=242.23726.102, package=com.jetbrains.python, isBundled=true), PluginDescriptor(name=ReStructuredText, id=org.jetbrains.plugins.rest, descriptorPath=plugin.xml, path=~/Apps/pycharm/plugins/restructuredtext, version=242.23726.102, package=com.intellij.restructuredtext, isBundled=true), PluginDescriptor(name=CSV Editor, id=net.seesharpsoft.intellij.plugins.csv, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/PyCharmCE2024.2/intellij-csv-validator, version=4.0.0, package=null, isBundled=false), ))
	at com.intellij.serviceContainer.ComponentManagerImpl.doInstantiateClass(ComponentManagerImpl.kt:918)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:894)
	at com.intellij.openapi.extensions.impl.SimpleConstructorInjectionAdapter.instantiateClass(XmlExtensionAdapter.kt:103)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.doCreateInstance(XmlExtensionAdapter.kt:52)
	... 57 more
Caused by: java.lang.NoClassDefFoundError: org/intellij/images/fileTypes/impl/ImageFileType
	at dev.ngocta.pycharm.odoo.file.OdooFileReferenceProvider.<clinit>(OdooFileReferenceProvider.java:115)
	at java.base/jdk.internal.misc.Unsafe.allocateInstance(Native Method)
	at java.base/java.lang.invoke.DirectMethodHandle.allocateInstance(DirectMethodHandle.java:501)
	at com.intellij.serviceContainer.ComponentManagerImpl.findConstructorAndInstantiateClass(ComponentManagerImpl.kt:900)
	at com.intellij.serviceContainer.ComponentManagerImpl.doInstantiateClass(ComponentManagerImpl.kt:909)
	... 60 more
Caused by: java.lang.ClassNotFoundException: org.intellij.images.fileTypes.impl.ImageFileType PluginClassLoader(plugin=PluginDescriptor(name=Odoo, id=dev.ngocta.pycharm-odoo, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/PyCharmCE2024.2/pycharm-odoo, version=2024.9.1.242, package=null, isBundled=false), packagePrefix=null, state=active, parents=PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.community.deprecated.extensions, descriptorPath=intellij.python.community.deprecated.extensions.xml, path=~/Apps/pycharm/plugins/python-ce, version=242.23726.102, package=com.jetbrains.extensions, isBundled=true), PluginDescriptor(name=ReStructuredText, id=org.jetbrains.plugins.rest, moduleName=intellij.restructuredtext.python, descriptorPath=intellij.restructuredtext.python.xml, path=~/Apps/pycharm/plugins/restructuredtext, version=242.23726.102, package=com.intellij.restructuredtext.python, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.terminal, descriptorPath=intellij.python.terminal.xml, path=~/Apps/pycharm/plugins/python-ce, version=242.23726.102, package=com.intellij.python.terminal, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.markdown, descriptorPath=intellij.python.markdown.xml, path=~/Apps/pycharm/plugins/python-ce, version=242.23726.102, package=com.intellij.python.markdown, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.langInjection, descriptorPath=intellij.python.langInjection.xml, path=~/Apps/pycharm/plugins/python-ce, version=242.23726.102, package=com.intellij.python.langInjection, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.grazie, descriptorPath=intellij.python.grazie.xml, path=~/Apps/pycharm/plugins/python-ce, version=242.23726.102, package=com.intellij.python.grazie, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.featuresTrainer, descriptorPath=intellij.python.featuresTrainer.xml, path=~/Apps/pycharm/plugins/python-ce, version=242.23726.102, package=com.intellij.python.featuresTrainer, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.copyright, descriptorPath=intellij.python.copyright.xml, path=~/Apps/pycharm/plugins/python-ce, version=242.23726.102, package=com.intellij.python.copyright, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.community.plugin.minorRider, descriptorPath=intellij.python.community.plugin.minorRider.xml, path=~/Apps/pycharm/plugins/python-ce, version=242.23726.102, package=com.intellij.python.community.plugin.minorRider, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.community.plugin.minor, descriptorPath=intellij.python.community.plugin.minor.xml, path=~/Apps/pycharm/plugins/python-ce, version=242.23726.102, package=com.intellij.python.community.plugin.minor, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.community.plugin.java, descriptorPath=intellij.python.community.plugin.java.xml, path=~/Apps/pycharm/plugins/python-ce, version=242.23726.102, package=com.intellij.python.community.plugin.java, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.community.plugin.impl, descriptorPath=intellij.python.community.plugin.impl.xml, path=~/Apps/pycharm/plugins/python-ce, version=242.23726.102, package=com.intellij.python.community.plugin.impl, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.community.impl.huggingFace, descriptorPath=intellij.python.community.impl.huggingFace.xml, path=~/Apps/pycharm/plugins/python-ce, version=242.23726.102, package=com.intellij.python.community.impl.huggingFace, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.community.communityOnly, descriptorPath=intellij.python.community.communityOnly.xml, path=~/Apps/pycharm/plugins/python-ce, version=242.23726.102, package=com.intellij.python.community.communityOnly, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.commandInterface, descriptorPath=intellij.commandInterface.xml, path=~/Apps/pycharm/plugins/python-ce, version=242.23726.102, package=com.intellij.commandInterface, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.impl, descriptorPath=intellij.platform.vcs.impl.xml, path=~/Apps/pycharm/lib, version=242.23726.102, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.log.impl, descriptorPath=intellij.platform.vcs.log.impl.xml, path=~/Apps/pycharm/lib, version=242.23726.102, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.dvcs.impl, descriptorPath=intellij.platform.vcs.dvcs.impl.xml, path=~/Apps/pycharm/lib, version=242.23726.102, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.collaborationTools, descriptorPath=intellij.platform.collaborationTools.xml, path=~/Apps/pycharm/lib, version=242.23726.102, package=null, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, descriptorPath=plugin.xml, path=~/Apps/pycharm/plugins/python-ce, version=242.23726.102, package=com.jetbrains.python, isBundled=true), PluginDescriptor(name=ReStructuredText, id=org.jetbrains.plugins.rest, descriptorPath=plugin.xml, path=~/Apps/pycharm/plugins/restructuredtext, version=242.23726.102, package=com.intellij.restructuredtext, isBundled=true), PluginDescriptor(name=CSV Editor, id=net.seesharpsoft.intellij.plugins.csv, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/PyCharmCE2024.2/intellij-csv-validator, version=4.0.0, package=null, isBundled=false), )
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:157)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 65 more

```

**Comment by trinhanhngoc** [comment]
Hello @Jerther ,

You are using PyCharm Professional or PyCharm Community?

**Comment by trinhanhngoc** [comment]
@Jerther ,

I just reproduced the issue with PyCharm Community 2024.2.4. Thanks for the report. This will be fixed in the next version.

**Comment by Jerther** [comment]
> Hello @Jerther ,
> 
> You are using PyCharm Professional or PyCharm Community?

Sorry; Community.

**Comment by trinhanhngoc** [comment]
@Jerther ,

The new version 2024.9.2 has been released with the fix.
