### ISSUE TITLE
Error on Run/Debug: java.util.MissingResourceException: Registry key python.use.targets.api is not defined

### ISSUE THREAD

**Issue by sreisich** [trinhanhngoc/pycharm-odoo#512]
Since I updated PyCharm to 2024.3 I cannot use the Run/Debug anymore if I used Odoo as configuration
```
Worker exited due to exception

java.util.MissingResourceException: Registry key python.use.targets.api is not defined
	at com.intellij.openapi.util.registry.Registry.getBundleValue$intellij_platform_util(Registry.kt:363)
	at com.intellij.openapi.util.registry.RegistryValue.resolveRequiredValue(RegistryValue.kt:198)
	at com.intellij.openapi.util.registry.RegistryValue.asBoolean(RegistryValue.kt:49)
	at com.intellij.openapi.util.registry.Registry$Companion.is(Registry.kt:85)
	at com.intellij.openapi.util.registry.Registry.is(Registry.kt)
	at dev.ngocta.pycharm.odoo.python.run.OdooPythonCommandLineState.emulateTerminal(OdooPythonCommandLineState.java:92)
	at dev.ngocta.pycharm.odoo.python.run.OdooPythonCommandLineState.startProcess(OdooPythonCommandLineState.java:49)
	at com.jetbrains.python.run.PythonCommandLineState.execute(PythonCommandLineState.java:232)
	at com.jetbrains.python.run.PythonCommandLineState.execute(PythonCommandLineState.java:179)
	at com.jetbrains.python.run.PythonRunner.lambda$execute$1(PythonRunner.java:66)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:107)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:101)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

**Comment by trinhanhngoc** [comment]
Hello @sreisich ,

Thanks for the report. This bug will be fixed in the next version.

**Comment by sreisich** [comment]
@trinhanhngoc Thank you very much for you really good work!

**Comment by trinhanhngoc** [comment]
Hello @sreisich,

The new version 2024.9.3 has been released with the fix for this issue.
