### ISSUE TITLE
java.lang.IllegalStateException: removeContentEntry

### ISSUE THREAD

**Issue by jerzyk** [trinhanhngoc/pycharm-odoo#524]
I'm getting this exception from time to time:

```
java.lang.IllegalStateException: removeContentEntry: removed content entry url 'file:///Users/jj/Library/Application Support/JetBrains/PyCharm2024.3/plugins/Odoo/stubs/odoo-stubs16' still exists after removing
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.roots.ModifiableRootModelBridgeImpl.removeContentEntry(ModifiableRootModelBridgeImpl.kt:250)
	at dev.ngocta.pycharm.odoo.python.stubs.OdooStubsUpdater.lambda$updateModule$3(OdooStubsUpdater.java:87)
	at com.intellij.openapi.roots.ModuleRootModificationUtil.modifyModel(ModuleRootModificationUtil.java:163)
	at dev.ngocta.pycharm.odoo.python.stubs.OdooStubsUpdater.updateModule(OdooStubsUpdater.java:82)
	at dev.ngocta.pycharm.odoo.python.stubs.OdooStubsUpdater.lambda$updateProject$0(OdooStubsUpdater.java:51)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at com.intellij.util.concurrency.ContextCallable.lambda$call$1(ContextCallable.java:74)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:83)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:249)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:227)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:212)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

**Comment by trinhanhngoc** [comment]
Hello @jerzyk ,

I am not sure why you are getting that exception. Your problem is the same as #471. You can find the solution in there.
