### ISSUE TITLE
Assertion failed: Text of a single string literal node expected

### ISSUE THREAD

**Issue by aqeebimtiaz** [trinhanhngoc/pycharm-odoo#71]
Getting the following error whenever I start the IDE & the plugin is not working anymore.

`java.lang.Throwable: Assertion failed: Text of a single string literal node expected
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:218)
	at com.jetbrains.python.psi.PyStringLiteralUtil.getContentRange(PyStringLiteralUtil.java:128)
	at com.jetbrains.python.psi.impl.PyPlainStringElementImpl.getContentRange(PyPlainStringElementImpl.java:48)
	at com.jetbrains.python.psi.impl.PyStringLiteralDecoder.decodeContent(PyStringLiteralDecoder.java:70)
	at com.jetbrains.python.psi.impl.PyPlainStringElementImpl.getDecodedFragments(PyPlainStringElementImpl.java:42)
	at com.jetbrains.python.psi.impl.PyStringLiteralExpressionImpl.lambda$getDecodedFragments$2(PyStringLiteralExpressionImpl.java:79)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517)
	at one.util.streamex.AbstractStreamEx.toArray(AbstractStreamEx.java:389)
	at one.util.streamex.AbstractStreamEx.toList(AbstractStreamEx.java:1313)
	at com.jetbrains.python.psi.impl.PyStringLiteralExpressionImpl.getDecodedFragments(PyStringLiteralExpressionImpl.java:84)
	at com.jetbrains.python.psi.impl.PyStringLiteralExpressionImpl.getStringValue(PyStringLiteralExpressionImpl.java:127)
	at com.jetbrains.python.psi.PyUtil.dictValue(PyUtil.java:1228)
	at dev.ngocta.pycharm.odoo.model.OdooModelUtils.doGetRecordValueContextResolver(OdooModelUtils.java:536)
	at dev.ngocta.pycharm.odoo.model.OdooModelUtils.lambda$getRecordValueContextResolver$9(OdooModelUtils.java:472)
	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValue(OdooUtils.java:220)
	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValue(OdooUtils.java:231)
	at dev.ngocta.pycharm.odoo.OdooUtils.getCachedValue(OdooUtils.java:205)
	at dev.ngocta.pycharm.odoo.model.OdooModelUtils.getRecordValueContextResolver(OdooModelUtils.java:471)
	at dev.ngocta.pycharm.odoo.model.field.OdooFieldReferenceContributor$10.accepts(OdooFieldReferenceContributor.java:220)
	at dev.ngocta.pycharm.odoo.model.field.OdooFieldReferenceContributor$10.accepts(OdooFieldReferenceContributor.java:212)
	at com.intellij.patterns.ObjectPattern.accepts(ObjectPattern.java:51)
	at com.intellij.psi.impl.source.resolve.reference.NamedObjectProviderBinding.addMatchingProviders(NamedObjectProviderBinding.java:90)
	at com.intellij.psi.impl.source.resolve.reference.SimpleProviderBinding.addAcceptableReferenceProviders(SimpleProviderBinding.java:26)
	at com.intellij.psi.impl.source.resolve.reference.PsiReferenceRegistrarImpl.getPairsByElement(PsiReferenceRegistrarImpl.java:180)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:139)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.lambda$getReferencesFromProviders$0(ReferenceProvidersRegistry.java:39)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:38)
	at com.jetbrains.python.psi.impl.PyStringLiteralExpressionImpl.getReferences(PyStringLiteralExpressionImpl.java:196)
	at com.intellij.codeInsight.highlighting.HyperlinkAnnotator.annotate(HyperlinkAnnotator.java:42)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:131)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:108)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.lambda$runHighlightVisitorsForInjected$5(InjectedGeneralHighlightingPass.java:368)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:93)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.runHighlightVisitorsForInjected(InjectedGeneralHighlightingPass.java:365)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.addInjectedPsiHighlights(InjectedGeneralHighlightingPass.java:243)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.lambda$addInjectedPsiHighlights$4(InjectedGeneralHighlightingPass.java:206)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1084)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:83)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:181)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:83)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)`

**Comment by trinhanhngoc** [comment]
Hi @aqeebimtiaz , does the above error only occur with a specific file or with any file opened at startup ?

**Comment by aqeebimtiaz** [comment]
Hi @trinhanhngoc ! This happens with any file I open up at the startup of PyCharm, Tried with different projects.

**Comment by trinhanhngoc** [comment]
Hi @aqeebimtiaz Can you provide a file that causes the error so I can check on my machine?

**Comment by scwall** [comment]
Hello I updated my pycharm ide and indeed I have the same problem on different projects at the opening 
```
java.lang.Throwable: Assertion failed: Text of a single string literal node expected
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:218)
	at com.jetbrains.python.psi.PyStringLiteralUtil.getContentRange(PyStringLiteralUtil.java:128)
	at com.jetbrains.python.psi.impl.PyPlainStringElementImpl.getContentRange(PyPlainStringElementImpl.java:48)
	at com.jetbrains.python.psi.impl.PyStringLiteralDecoder.decodeContent(PyStringLiteralDecoder.java:70)
	at com.jetbrains.python.psi.impl.PyPlainStringElementImpl.getDecodedFragments(PyPlainStringElementImpl.java:42)
	at com.jetbrains.python.psi.impl.PyStringLiteralExpressionImpl.lambda$getDecodedFragments$2(PyStringLiteralExpressionImpl.java:79)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517)
	at one.util.streamex.AbstractStreamEx.toArray(AbstractStreamEx.java:389)
	at one.util.streamex.AbstractStreamEx.toList(AbstractStreamEx.java:1313)
	at com.jetbrains.python.psi.impl.PyStringLiteralExpressionImpl.getDecodedFragments(PyStringLiteralExpressionImpl.java:84)
	at com.jetbrains.python.psi.impl.PyStringLiteralExpressionImpl.getStringValue(PyStringLiteralExpressionImpl.java:127)
	at com.jetbrains.python.psi.PyUtil.dictValue(PyUtil.java:1228)
	at dev.ngocta.pycharm.odoo.model.OdooModelUtils.doGetRecordValueContextResolver(OdooModelUtils.java:538)
	at dev.ngocta.pycharm.odoo.model.OdooModelUtils.lambda$getRecordValueContextResolver$9(OdooModelUtils.java:474)
	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValue(OdooUtils.java:222)
	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValue(OdooUtils.java:233)
	at dev.ngocta.pycharm.odoo.OdooUtils.getCachedValue(OdooUtils.java:207)
	at dev.ngocta.pycharm.odoo.model.OdooModelUtils.getRecordValueContextResolver(OdooModelUtils.java:473)
	at dev.ngocta.pycharm.odoo.model.field.OdooFieldReferenceContributor$10.accepts(OdooFieldReferenceContributor.java:226)
	at dev.ngocta.pycharm.odoo.model.field.OdooFieldReferenceContributor$10.accepts(OdooFieldReferenceContributor.java:218)
	at com.intellij.patterns.ObjectPattern.accepts(ObjectPattern.java:51)
	at com.intellij.psi.impl.source.resolve.reference.NamedObjectProviderBinding.addMatchingProviders(NamedObjectProviderBinding.java:90)
	at com.intellij.psi.impl.source.resolve.reference.SimpleProviderBinding.addAcceptableReferenceProviders(SimpleProviderBinding.java:26)
	at com.intellij.psi.impl.source.resolve.reference.PsiReferenceRegistrarImpl.getPairsByElement(PsiReferenceRegistrarImpl.java:180)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:139)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.lambda$getReferencesFromProviders$0(ReferenceProvidersRegistry.java:39)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:38)
	at com.jetbrains.python.psi.impl.PyStringLiteralExpressionImpl.getReferences(PyStringLiteralExpressionImpl.java:196)
	at com.intellij.codeInsight.highlighting.HyperlinkAnnotator.annotate(HyperlinkAnnotator.java:42)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:131)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:108)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.lambda$runHighlightVisitorsForInjected$5(InjectedGeneralHighlightingPass.java:368)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:93)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.runHighlightVisitorsForInjected(InjectedGeneralHighlightingPass.java:365)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.addInjectedPsiHighlights(InjectedGeneralHighlightingPass.java:243)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.lambda$addInjectedPsiHighlights$4(InjectedGeneralHighlightingPass.java:206)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1084)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:83)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:181)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:83)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

```
Following exceptions happened soon after this one, most probably they are induced.


2022-03-23T10:42:35.491
java.lang.Throwable: Assertion failed: Text of a single string literal node expected
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:218)
	at com.jetbrains.python.psi.PyStringLiteralUtil.getContentRange(PyStringLiteralUtil.java:128)
	at com.jetbrains.python.psi.impl.PyPlainStringElementImpl.getContentRange(PyPlainStringElementImpl.java:48)
	at com.jetbrains.python.psi.impl.PyStringLiteralDecoder.decodeContent(PyStringLiteralDecoder.java:70)
	at com.jetbrains.python.psi.impl.PyPlainStringElementImpl.getDecodedFragments(PyPlainStringElementImpl.java:42)
	at com.jetbrains.python.psi.impl.PyStringLiteralExpressionImpl.lambda$getDecodedFragments$2(PyStringLiteralExpressionImpl.java:79)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517)
	at one.util.streamex.AbstractStreamEx.toArray(AbstractStreamEx.java:389)
	at one.util.streamex.AbstractStreamEx.toList(AbstractStreamEx.java:1313)
	at com.jetbrains.python.psi.impl.PyStringLiteralExpressionImpl.getDecodedFragments(PyStringLiteralExpressionImpl.java:84)
	at com.jetbrains.python.psi.impl.PyStringLiteralExpressionImpl.getStringValue(PyStringLiteralExpressionImpl.java:127)
	at com.jetbrains.python.psi.PyUtil.dictValue(PyUtil.java:1228)
	at dev.ngocta.pycharm.odoo.model.OdooModelUtils.doGetRecordValueContextResolver(OdooModelUtils.java:538)
	at dev.ngocta.pycharm.odoo.model.OdooModelUtils.lambda$getRecordValueContextResolver$9(OdooModelUtils.java:474)
	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValue(OdooUtils.java:222)
	at dev.ngocta.pycharm.odoo.OdooUtils.getParameterizedCachedValue(OdooUtils.java:233)
	at dev.ngocta.pycharm.odoo.OdooUtils.getCachedValue(OdooUtils.java:207)
	at dev.ngocta.pycharm.odoo.model.OdooModelUtils.getRecordValueContextResolver(OdooModelUtils.java:473)
	at dev.ngocta.pycharm.odoo.model.field.OdooFieldReferenceContributor$10.accepts(OdooFieldReferenceContributor.java:226)
	at dev.ngocta.pycharm.odoo.model.field.OdooFieldReferenceContributor$10.accepts(OdooFieldReferenceContributor.java:218)
	at com.intellij.patterns.ObjectPattern.accepts(ObjectPattern.java:51)
	at com.intellij.psi.impl.source.resolve.reference.NamedObjectProviderBinding.addMatchingProviders(NamedObjectProviderBinding.java:90)
	at com.intellij.psi.impl.source.resolve.reference.SimpleProviderBinding.addAcceptableReferenceProviders(SimpleProviderBinding.java:26)
	at com.intellij.psi.impl.source.resolve.reference.PsiReferenceRegistrarImpl.getPairsByElement(PsiReferenceRegistrarImpl.java:180)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:139)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.lambda$getReferencesFromProviders$0(ReferenceProvidersRegistry.java:39)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:44)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:38)
	at com.jetbrains.python.psi.impl.PyStringLiteralExpressionImpl.getReferences(PyStringLiteralExpressionImpl.java:196)
	at com.intellij.codeInsight.highlighting.HyperlinkAnnotator.annotate(HyperlinkAnnotator.java:42)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:131)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:108)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.lambda$runHighlightVisitorsForInjected$5(InjectedGeneralHighlightingPass.java:368)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:93)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.runHighlightVisitorsForInjected(InjectedGeneralHighlightingPass.java:365)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.addInjectedPsiHighlights(InjectedGeneralHighlightingPass.java:243)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.lambda$addInjectedPsiHighlights$4(InjectedGeneralHighlightingPass.java:206)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1084)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:83)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:181)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:83)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by trinhanhngoc** [comment]
Hi @scwall . Can you provide sample source code causing the error?. It's hard for me to fix because I can not reproduce it on my machine.

**Comment by aqeebimtiaz** [comment]
Hi, @scwall & @trinhanhngoc . I increased the memory limit on my PyCharm. This reduced the frequency of these errors popping up. @trinhanhngoc can you please check if the plugin is experiencing any memory leak or memory over usage?

One more thing I have noticed, the RAM usage gets really high from time to time. I have tried with enabling this plugin only. It doesn't matter what type of file I'm opening, Python or XML.

**Comment by trinhanhngoc** [comment]
@aqeebimtiaz How much memory heap do you setup for your IDE? Mine is 3072M, more than enough for a huge project of more than 1000 modules for multiple Odoo versions.

**Comment by jcfernandez-890825** [comment]
@aqeebimtiaz I remember something like that, I think it could solve by increasing "Maximum Heap Size" to 4096MiB.

![image](https://user-images.githubusercontent.com/28876647/159934629-82f974f3-952e-4e06-b72a-2503a902f01b.png)


![image](https://user-images.githubusercontent.com/28876647/159932770-85709e36-c425-4051-98c2-033a0f14572c.png)

Just put that amount and hit "Save and Restart"

**Comment by scwall** [comment]
Ok thanks for your messages. I don't have any particular file, no matter what file I open it causes the problem

**Comment by aqeebimtiaz** [comment]
@jcfernandez-890825 Thanks for the input!

@trinhanhngoc I have put around 2500 MB as Heap Size allocated on PyCharm. I increased from 1500 to 2500 recently which reduced the frequency of the error message.

**Comment by jcfernandez-890825** [comment]
> @jcfernandez-890825 Thanks for the input!
> 
> @trinhanhngoc I have put around 2500 MB as Heap Size allocated on PyCharm. I increased from 1500 to 2500 recently which reduced the frequency of the error message.

Then my advice is to keep increasing the value.
Regards.
😉

**Comment by trinhanhngoc** [comment]
Hi @aqeebimtiaz @scwall 

The version 2022.5 has been released with the fix for this longstanding issue. Thank you all for your report.

**Comment by aqeebimtiaz** [comment]
Thank you! ❤️
