### ISSUE TITLE
pycharm error

### ISSUE THREAD

**Issue by scwall** [trinhanhngoc/pycharm-odoo#75]
Hello i have a error
```
java.lang.Throwable: Non-idempotent computation: it returns different results when invoked multiple times or on different threads:
  3 != 5
  which is length of [PyFile:models.py@0, PyFile:models.py@0, PyImportElement:models@-1000] and [PyFile:models.py@0, PyFile:models.py@0, PyFile:models.py@0, PyFile:models.py@0, PyImportElement:models@-1000]

Recomputation gives [Lcom.intellij.psi.ResolveResult;@1a7b789e (class [Lcom.intellij.psi.ResolveResult;) which is equivalent to 'fresh'
Recomputation log:
  Resolving dev.ngocta.pycharm.odoo.python.psi.OdooPyReference@644bb9b9 of class dev.ngocta.pycharm.odoo.python.psi.OdooPyReference
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.util.IdempotenceChecker.reportFailure(IdempotenceChecker.java:89)
	at com.intellij.util.IdempotenceChecker.checkEquivalence(IdempotenceChecker.java:76)
	at com.intellij.psi.impl.source.resolve.ResolveCache.cache(ResolveCache.java:322)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:249)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:169)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:162)
	at com.jetbrains.python.psi.impl.references.PyReferenceImpl.multiResolve(PyReferenceImpl.java:94)
	at com.jetbrains.python.psi.impl.references.PyReferenceImpl.resolve(PyReferenceImpl.java:73)
	at dev.ngocta.pycharm.odoo.model.OdooLambdaTypeProvider.getReferenceExpressionType(OdooLambdaTypeProvider.java:22)
	at com.jetbrains.python.psi.impl.PyReferenceExpressionImpl.getTypeFromProviders(PyReferenceExpressionImpl.java:383)
	at com.jetbrains.python.psi.impl.PyReferenceExpressionImpl.getType(PyReferenceExpressionImpl.java:217)
	at com.jetbrains.python.psi.types.TypeEvalContext.lambda$getType$0(TypeEvalContext.java:177)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.jetbrains.python.psi.types.TypeEvalContext.getType(TypeEvalContext.java:166)
	at com.jetbrains.python.codeInsight.stdlib.PyNamedTupleTypeProvider$Companion.getFieldTypeForNamedTupleAsTarget(PyNamedTupleTypeProvider.kt:87)
	at com.jetbrains.python.codeInsight.stdlib.PyNamedTupleTypeProvider$Companion.access$getFieldTypeForNamedTupleAsTarget(PyNamedTupleTypeProvider.kt:53)
	at com.jetbrains.python.codeInsight.stdlib.PyNamedTupleTypeProvider.getReferenceExpressionType(PyNamedTupleTypeProvider.kt:31)
	at com.jetbrains.python.psi.impl.PyReferenceExpressionImpl.getTypeFromProviders(PyReferenceExpressionImpl.java:383)
	at com.jetbrains.python.psi.impl.PyReferenceExpressionImpl.getType(PyReferenceExpressionImpl.java:217)
	at com.jetbrains.python.psi.types.TypeEvalContext.lambda$getType$0(TypeEvalContext.java:177)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.jetbrains.python.psi.types.TypeEvalContext.getType(TypeEvalContext.java:166)
	at com.jetbrains.python.psi.impl.PyClassImpl.fillSuperClassesSwitchingToAst(PyClassImpl.java:1377)
	at com.jetbrains.python.psi.impl.PyClassImpl.doGetSuperClassTypes(PyClassImpl.java:1361)
	at com.jetbrains.python.psi.PyUtil.getNullableParameterizedCachedValue(PyUtil.java:676)
	at com.jetbrains.python.psi.PyUtil.getParameterizedCachedValue(PyUtil.java:654)
	at com.jetbrains.python.psi.impl.PyClassImpl.getSuperClassTypes(PyClassImpl.java:1349)
	at com.jetbrains.python.psi.types.PyClassTypeImpl.getSuperClassTypes(PyClassTypeImpl.java:119)
	at com.jetbrains.python.psi.impl.PyClassImpl.mroLinearize(PyClassImpl.java:414)
	at com.jetbrains.python.psi.impl.PyClassImpl.getMROAncestorTypes(PyClassImpl.java:1646)
	at com.jetbrains.python.psi.impl.PyClassImpl.lambda$getAncestorTypesWithMetaClassInstances$10(PyClassImpl.java:1446)
	at com.jetbrains.python.psi.PyUtil.getNullableParameterizedCachedValue(PyUtil.java:676)
	at com.jetbrains.python.psi.PyUtil.getParameterizedCachedValue(PyUtil.java:654)
	at com.jetbrains.python.psi.impl.PyClassImpl.getAncestorTypesWithMetaClassInstances(PyClassImpl.java:1442)
	at com.jetbrains.python.psi.impl.PyClassImpl.getAncestorTypes(PyClassImpl.java:1437)
	at com.jetbrains.extensions.python.PyClassExtKt.inherits(PyClassExt.kt:28)
	at com.jetbrains.extensions.python.PyClassExtKt.inherits(PyClassExt.kt:30)
	at com.jetbrains.python.testing.PythonUnitTestDetectorsKt.isUnitTestCaseClass(PythonUnitTestDetectors.kt:23)
	at com.jetbrains.python.testing.PythonUnitTestDetectorsKt.isTestClass(PythonUnitTestDetectors.kt:31)
	at com.jetbrains.python.testing.PythonUnitTestDetectorsBasedOnSettings.isTestClass(PythonUnitTestDetectorsBasedOnSettings.java:85)
	at com.jetbrains.python.testing.PyTestsSharedKt.isTestElement(PyTestsShared.kt:95)
	at com.jetbrains.python.testing.PyTestLineMarkerContributor.getInfo(PyTestLineMarkerContributor.kt:25)
	at com.intellij.execution.lineMarker.RunLineMarkerProvider.getLineMarkerInfo(RunLineMarkerProvider.java:58)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:155)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:82)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:81)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:77)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:414)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:407)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:406)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:382)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:380)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by trinhanhngoc** [comment]
Hi @scwall , It looks like you are using an old version of the Odoo plugin. Please try updating the Odoo plugin to the latest version.

**Comment by scwall** [comment]
Hello it does not propose me to be able to update 

![image](https://user-images.githubusercontent.com/30811539/158628200-00aa68c3-7cef-4f0e-b26f-c0959a657aab.png)

**Comment by trinhanhngoc** [comment]
> Hello it does not propose me to be able to update
> 
> ![image](https://user-images.githubusercontent.com/30811539/158628200-00aa68c3-7cef-4f0e-b26f-c0959a657aab.png)

What version of PyCharm are you using?

**Comment by scwall** [comment]
Hello
2021.2.3

**Comment by trinhanhngoc** [comment]
Hi @scwall , the latest version of plugin (2022.1) supports PyCharm 2021.3+. You can update PyCharm and the Odoo plugin to the latest version to enjoy the new features and bug fixes.

**Comment by scwall** [comment]
Hi @trinhanhngoc  thanks for your feedback 

but I can't do that, I currently have other plugins that are not up to date, I must always have some lag in versions. However I receive the updates of the other plugins even if I am two or sometimes three versions behind. Is there a reason that I have to update my ide?

Thanks in advance

**Comment by trinhanhngoc** [comment]
> Hi @trinhanhngoc thanks for your feedback
> 
> but I can't do that, I currently have other plugins that are not up to date, I must always have some lag in versions. However I receive the updates of the other plugins even if I am two or sometimes three versions behind. Is there a reason that I have to update my ide?
> 
> Thanks in advance

Hi @scwall . In future versions, I will try to keep the Odoo plugin compatible with more versions of PyCharm. For now, I will try making a new build of the Odoo plugin compatible with PyCharm 2021.2.

**Comment by trinhanhngoc** [comment]
Duplicated #3

**Comment by scwall** [comment]
@trinhanhngoc thanks for response
