### ISSUE TITLE
Error while creating a XML record

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#80]
stacktrace.txt
```
java.lang.ClassCastException: class dev.ngocta.pycharm.odoo.xml.dom.OdooDomViewField$$EnhancerByJetBrainsMainCglib$$63fe9e7a cannot be cast to class dev.ngocta.pycharm.odoo.xml.dom.OdooDomFieldAssignment (dev.ngocta.pycharm.odoo.xml.dom.OdooDomViewField$$EnhancerByJetBrainsMainCglib$$63fe9e7a and dev.ngocta.pycharm.odoo.xml.dom.OdooDomFieldAssignment are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @74b6dbba)
	at dev.ngocta.pycharm.odoo.xml.dom.OdooDomRecord.findField(OdooDomRecord.java:21)
	at dev.ngocta.pycharm.odoo.xml.dom.OdooDomRecord.getViewModel(OdooDomRecord.java:38)
	at dev.ngocta.pycharm.odoo.xml.dom.OdooDomRecordLike.getRecordExtraInfo(OdooDomRecordLike.java:60)
	at dev.ngocta.pycharm.odoo.xml.dom.OdooDomRecordLike.getRecord(OdooDomRecordLike.java:73)
	at dev.ngocta.pycharm.odoo.xml.OdooXmlLineMarkerProvider.getChildrenViewRecordLineMarker(OdooXmlLineMarkerProvider.java:95)
	at dev.ngocta.pycharm.odoo.xml.OdooXmlLineMarkerProvider.collectSlowLineMarkers(OdooXmlLineMarkerProvider.java:54)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:195)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:90)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:115)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:85)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:414)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1084)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:407)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:406)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:382)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:181)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:380)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:184)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 , what version of PyCharm are you using?

**Comment by jcfernandez-890825** [comment]
```
PyCharm 2021.3.3 (Professional Edition)
Build #PY-213.7172.26, built on March 16, 2022
Licensed to Juan Carlos Fernández
Subscription is active until November 13, 2022.
Runtime version: 11.0.14.1+1-b1751.46 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-100-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Non-Bundled Plugins:
    net.seesharpsoft.intellij.plugins.csv (2.18.2)
    com.tabnine.TabNine (0.5.23)
    ru.mobiledev.plugins.uigd (1.2)
    XPathView (213.5744.122)
    Statistic (4.1.10)
    zielu.gittoolbox (212.8.9)
    com.github.jk1.ytplugin (2021.4.163)
    dev.ngocta.pycharm-odoo (2022.2)

Current Desktop: X-Cinnamon
```

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 

Are you still getting this error with the latest version of the Odoo plugin?

**Comment by jcfernandez-890825** [comment]
No, you can close this. Thanks for the fixes.
